datascience/requirements-dev.txt, datascience/requirements.txt
`pip install` breaks when hashes are included in requirement.txt.
Unclear why, see https://github.com/cjolowicz/hypermodern-python/issues/174 and https://github.com/python-poetry/poetry/issues/3472
Locally, if managing dependencies with poetry, requirements.txt without hashes can be generated by passing `--without-hashes` to `poetry export`:
```
poetry export -o requirements.txt --without-hashes
poetry export -o requirements-dev.txt --without-hashes --dev
```
=> Remove hashes from requirements to fix pip install

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/LastPositionEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBLastPositionRepository.kt, backend/src/main/resources/db/migration/internal/V0.34__Update_last_position_table.sql, datascience/src/pipeline/flows/last_positions.py, datascience/src/pipeline/queries/monitorfish/last_positions.sql
* Add ircs as one of the possible identifiers (along with cfr and external immat) when extracting last positions from `positions` table
* Use the newly added `id` field (generated by python flow)  as key in last_positions table
=> Add id in last position

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/VesselIdentifier.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/last_position/LastPosition.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/PositionRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/GetVessel.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/BffController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/ControllersExceptionHandler.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/LastPositionDataOutput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/MissingParameterApiError.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/LastPositionEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPositionRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaVesselRepository.kt, backend/src/main/resources/db/migration/internal/V0.38__Update_last_positions_table.sql, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/GetVesselUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/BffControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLastPositionRepositoryITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPositionRepositoryITests.kt, datascience/src/pipeline/flows/last_positions.py, datascience/src/pipeline/processing.py, datascience/src/pipeline/queries/monitorfish/last_positions.sql, datascience/src/pipeline/queries/ocan/flotteurs.sql, frontend/src/api/fetch.js, frontend/src/domain/entities/vessel.js
* Add `vessel_identifier` column to `last_positions` table in last_positions flow to indicate which identifier to use for track retrieval
* Fix flag_state filter on GB vessels with incorrect VMS positions
* Filter non professional vessels in navpro extract
=> Fix track vessel id

infra/remote/README.md, infra/remote/update_app_image/README.md, infra/remote/update_app_image/update_app_image.sh
Ajoute un script cron de MAJ de l'application (seulement l'app, pas prefect) pour faire des bugfixes en PROD en crééant une nouvelle image qui incrémente le numéro de patch de la version.
Par exemple, de `v1.0.2` à v1.0.3
=> Add automatic app updater script

backend/src/main/resources/db/migration/internal/V0.59__Update_ports_table.sql, backend/src/main/resources/db/migration/internal/V0.60__Update_controls_table.sql, backend/src/main/resources/db/migration/layers/V0.58__Create_facade_areas_table.sql
Add FAO areas and façade to `ports` and `controls` tables.
=> Migrations for controls stats

datascience/src/pipeline/flows/ers.py
=> Remove drop duplicates on operation_number for parsed logbook lines

datascience/src/pipeline/schedules.py
- Resolve #797
---
Augmentation de la fréquence de synchronisation pour limiter le délai entre la mise à jour dans Gina et dans Monitorfish sur le permis de nav.
=> Run vessels flow every 3 hours

frontend/src/domain/entities/layers.js, frontend/src/domain/shared_slices/Layer.js, frontend/src/domain/types/layer.js, frontend/src/domain/use_cases/hideLayer.js, frontend/src/domain/use_cases/showAdministrativeLayer.js, frontend/src/domain/use_cases/showRegulationToEdit.js, frontend/src/domain/use_cases/showRegulatoryLayer.js, frontend/src/features/backoffice/LawType.js, frontend/src/features/commonComponents/MapPropertyTrigger.js, frontend/src/features/commonStyles/icons/ChevronIcon.style.js, frontend/src/features/interest_points/InterestPoint.js, frontend/src/features/layers/administrative/AdministrativeLayerGroup.js, frontend/src/features/layers/administrative/AdministrativeLayers.js, frontend/src/features/layers/base/BaseLayers.js, frontend/src/features/layers/regulatory/RegulatoryLayerZone.js, frontend/src/features/layers/regulatory/RegulatoryLayers.js, frontend/src/features/measurements/Measurement.js, frontend/src/features/vessel_filters/Filter.js, frontend/src/features/vessel_filters/VesselFilters.js, frontend/src/features/vessel_search/VesselsSearch.js, frontend/src/features/vessel_sidebar/controls/YearControls.js, frontend/src/features/vessel_sidebar/fishing_activities/ers_messages/ERSMessageSpecies.js, frontend/src/features/vessel_sidebar/fishing_activities/ers_messages_resumes/ERSMessageResumeHeader.js, frontend/src/features/vessel_sidebar/fishing_activities/ers_messages_resumes/SpeciesAndWeightChart.js, frontend/src/features/vessel_sidebar/risk_factor/RiskFactorResume.js, frontend/src/features/vessel_visibility/VesselVisibility.js, frontend/src/layers/AdministrativeLayers.js, frontend/src/layers/RegulatoryLayers.js
[Description]
- Les couches Regulatory et Admin n'utilisent plus state.layers comme passe-plat. La mise à jour des couches se fait uniquement en regardant les changements sur showedLayers
- utilisation des transient props sur les icones quand c'est possible
- ajout du raccourci de création de filtres
- closes #518 
- Resolve #666
- Resolves #613 
----
=> Remove OL layers objects from redux

datascience/src/pipeline/schedules.py
* Augmente la fenêtre temporelle de requête pour le flow `last_positions` :
* mise à jour chaque minute avec requête sur les positions émises au cours des 30 dernières minutes - suffisant pour la plupart des cas, les signaux VMS des anglais arrivent avec ~15 minutes de décalage, les autres nationalités plutôt ~5 minutes
* mise à jour chaque heure avec requête sur les positions émises au cours des 4 dernières heures, pour rattraper les exceptionnels retards plus importants
* Augmente la fréquence de synchronisation de `regulations` (pas nécessaire de synchroniser toutes les minutes, toutes les 5 minutes est suffisant)
- Resolve #855
=> Increase last positions time window

datascience/src/pipeline/flows/last_positions.py, datascience/src/pipeline/processing.py, datascience/src/pipeline/queries/monitorfish/compute_last_positions.sql, datascience/tests/test_pipeline/test_flows/test_last_positions.py, datascience/tests/test_pipeline/test_processing.py
- Resolve #861 
----
Pour certains navires, on reçoit les signaux VMS plusieurs fois avec des identifiants différents. On peut par exemple recevoir pour un même navire les positions suivantes :
| date_time                   | cfr   | external_immatriculation   | ircs   |   latitude |   longitude |
|:-----------------------------|:------|:----------------------------------|:--------|------------:|------------:|
| 2021-01-01 11:12:00 | A     | I MMAT                             | callme |      45.23 |       -3.56 |
| 2021-01-01 11:12:00 | A     | i-mmat                              | callme |      45.23 |       -3.56 |
| 2021-01-01 12:12:00 | A     | I MMAT                            | callme |      45.36 |       -3.12 |
| 2021-01-01 12:12:00 | A     | i-mmat                             | …
=> Fix last positions

datascience/config.py, datascience/main.py, infra/configurations/prefect-server/backend.toml, infra/configurations/prefect-server/config.toml, infra/remote/crontab.txt, infra/remote/data-pipeline/int/start-flows.sh, infra/remote/data-pipeline/prod/start-flows.sh
=> Add healthcheck on monitorfish-pipeline-flows container

datascience/src/pipeline/flows/position_alerts.py, datascience/src/pipeline/queries/monitorfish/current_risk_factors.sql, datascience/tests/test_pipeline/test_flows/test_position_alerts.py
- Resolve #949 
Les navires pour lesquels on reçoit des positions mais qui n'ont pas de JPE et qui n'ont jamais fait l'objet de contrôles figurent dans la table `last_positions`, mais pas dans la table `risk_factors`. Pour ces navires, un facteur de risque par défaut est néanmoins présent dans la table `last_position`, donc il vaut mieux prendre les facteurs de risque dans cette table plutôt que dans `risk_factors`.
Inversement, `risk_factors` contient des facteurs de risque sur des navires qui n'émettent pas de positions (<12m) qui ne sont donc _pas_ dans la table `last_positions`, mais on ne lèvera jamais d'alertes de chalutage sur ces navires (ce n'est pas possible puisqu'on ne connait pas leur position) donc il n'est pas utile de prendre les facteurs de risque dans la table …
=> Take risk factors in last_positions table when raising alerts

datascience/src/pipeline/flows/missing_trip_numbers.py, datascience/src/pipeline/queries/monitorfish/missing_trip_numbers.sql, datascience/tests/test_pipeline/test_flows/test_missing_trip_numbers.py
- Resolve #1137
----
Règle deux problèmes : 
- ajoute une sécurité pour ne pas écraser de trip_numbers réels (non calculés)
- ajoute une valeur par défaut ('0') de trip_number pour les `COR` avant le premier `DAT`
=> Fix missing trip numbers

frontend/src/App.css, frontend/src/features/backoffice/edit_regulation/custom_form/CustomSelectComponent.js, frontend/src/features/backoffice/edit_regulation/fishing_period/TimeInterval.js, frontend/src/features/backoffice/edit_regulation/gear_regulation/RegulatedGear.js, frontend/src/features/backoffice/fleet_segments/NewFleetSegmentModal.js, frontend/src/features/backoffice/tableCells.js, frontend/src/features/commonComponents/StyledModalHeader.js, frontend/src/features/commonStyles/Backoffice.style.js, frontend/src/features/map/overlays/map_menu/TrackRangeModal.js, frontend/src/features/side_window/SideWindow.js, frontend/src/features/side_window/beacon_malfunctions/BeaconMalfunctionDetailsFollowUp.js, frontend/src/features/vessel_filters/SaveVesselFiltersModal.js, frontend/src/features/vessel_list/DownloadVesselListModal.js, frontend/src/features/vessel_list/VesselList.js, frontend/src/features/vessel_list/VesselListTable.js, frontend/src/features/vessel_list/tableCells.js, frontend/src/features/vessel_sidebar/actions/track_request/DateRange.js, frontend/src/features/vessel_sidebar/reporting/current/ConfirmDeletionModal.js, frontend/src/features/vessel_sidebar/risk_factor/RiskFactorExplanationModal.js, frontend/src/index.css
Pour ne pas bloquer la prochaine MEP (mercredi 27), j'ai fait les changements pour fix les points remontés sur la revue https://github.com/MTES-MCT/monitorfish/pull/1226#pullrequestreview-1033950198
Cela nous permet à court terme de ne pas avoir de régression sur les composants rsuite suite au passage à la v5, par contre il faudra sortir les styles proprement par la suite, en remboursant cette dette technique.
@ivangabriele Pourrais-tu regarder cette PR ?
----
=> Fix rsuite v5 styles

backend/src/main/resources/db/migration/layers/V0.157__Update_regulations_table.sql, datascience/src/pipeline/queries/cross/regulations.sql, frontend/cypress/e2e/backoffice_update_regulation.spec.ts, frontend/src/domain/entities/regulatory.js, frontend/src/features/backoffice/edit_regulation/EditRegulation.js, frontend/src/features/backoffice/edit_regulation/custom_form/CustomSelectComponent.js, frontend/src/features/backoffice/edit_regulation/fishing_period/FishingPeriodSection.js, frontend/src/features/backoffice/edit_regulation/gear_regulation/GearRegulation.js, frontend/src/features/backoffice/edit_regulation/species_regulation/SpeciesRegulation.js, infra/local/md5_trigger_function.sql
- Resolve #1329 
Migration:
```
ALTER TABLE public.regulations
ADD COLUMN other_info varchar;
CREATE OR REPLACE VIEW regulations_view AS
SELECT id,
law_type,
facade,
topic,
zone,
region,
other_info,
fishing_period,
species,
gears,
regulatory_references,
geometry_simplified,
row_hash,
next_id
FROM regulations;
ALTER TABLE regulations_view
RENAME COLUMN geometry_simplified to geometry;
```
Trigger :
```
DROP FUNCTION IF EXISTS prod.compute_reglementation_md5 CASCADE;
CREATE FUNCTION prod.compute_regulations_md5() RETURNS trigger AS $$
BEGIN
NEW.row_hash := md5(
COALESCE(NEW.law_type::text, '') ||
COALESCE(NEW.facade::text, '') ||
COALESCE(NEW.topic::text, '') ||
COALESCE(NEW.zone::text, '') ||
COALESCE(NEW.region::text, '') ||
COALESCE(NEW.other_info::text, '') || …
```
=> Add other info to regulations table

frontend/cypress/e2e/side_window/reporting_list/table.spec.ts, frontend/cypress/e2e/side_window/reporting_list/utils.ts, frontend/src/features/SideWindow/AlertListAndReportingList/ReportingList/constants.ts, frontend/src/features/SideWindow/AlertListAndReportingList/ReportingList/index.tsx, frontend/src/features/SideWindow/AlertListAndReportingList/index.tsx, frontend/src/features/SideWindow/SideWindowSubMenuLink.tsx, frontend/src/hooks/useTable/TableHead.tsx, frontend/src/hooks/useTable/TableHeadNext.tsx, frontend/src/hooks/useTable/index.tsx, frontend/src/ui/card-table/CardTable.tsx, frontend/src/ui/card-table/CardTableBody.tsx, frontend/src/ui/card-table/CardTableColumnTitle.tsx, frontend/src/ui/card-table/CardTableHeader.tsx, frontend/src/ui/card-table/CardTableRow.tsx
=> [Signalements] Le tri de la liste ne fonctionne plus

backend/src/main/resources/db/migration/internal/V0.232__Update_satellite_operators_statuses_view.sql
=> Passer la fenêtre de vérification de statut des opérateurs satellite de 48h à 24h

frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/src/api/utils.ts, frontend/src/features/SideWindow/MissionForm/utils.tsx, frontend/src/features/SideWindow/__tests__/utils.test.ts
=> [Missions] Correction du l'écriture de `mission_source`

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission_actions/MissionAction.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/input/AddMissionActionDataInput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/MissionActionDataOutput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/MissionActionEntity.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission_actions/MissionActionUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/AddMissionActionUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/DeleteMissionActionUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/GetMissionActionFacadeUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/GetVesselControlsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/TestUtils.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/UpdateMissionActionUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/MissionActionsControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/MissionsControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaMissionActionRepositoryITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/TestUtils.kt
=> [Contrôles] Correction de la sauvegarde du champ `is_from_poseidon`

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/InfractionRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/infraction/GetAllInfractions.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/InfractionController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/cache/CaffeineConfiguration.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaInfractionRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBInfractionRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/InfractionControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaInfractionRepositoryITests.kt
=> [Missions] Ajout des NATINFs CACEM 

datascience/src/pipeline/flows/recompute_controls_segments.py, datascience/tests/test_pipeline/test_flows/test_recompute_controls_segments.py
=> Réparation du flow `recompute_controls_segments`

frontend/cypress/e2e/side_window/mission_form/action_list.spec.ts, frontend/cypress/e2e/side_window/mission_form/sea_control.spec.ts, frontend/cypress/e2e/vessel_sidebar/controls.spec.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/Infraction.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/index.tsx, frontend/src/features/SideWindow/MissionForm/ActionList/Item.tsx, frontend/src/features/SideWindow/MissionForm/hooks/useGetNatinfsAsOptions.ts, frontend/src/features/VesselSidebar/Controls/Infraction.tsx
=> [Missions] Ajout du nom de l'infraction

frontend/cypress/e2e/side_window/mission_form/action_list.spec.ts, frontend/cypress/e2e/side_window/mission_form/air_control.spec.ts, frontend/cypress/e2e/side_window/mission_form/land_control.spec.ts, frontend/cypress/e2e/side_window/mission_form/sea_control.spec.ts, frontend/src/api/infraction.ts, frontend/src/domain/entities/controls.ts, frontend/src/domain/shared_slices/Infraction.ts, frontend/src/domain/types/infraction.ts, frontend/src/domain/types/missionAction.ts, frontend/src/domain/types/reporting.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/AirControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/LandControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/SeaControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/Infraction.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/InfractionForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/constants.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/index.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/types.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/GearsField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/LicencesAndLogbookField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/SpeciesField.tsx, frontend/src/features/SideWindow/MissionForm/ActionList/utils.tsx, frontend/src/features/SideWindow/MissionForm/shared/FieldsetGroupSeparator.tsx, frontend/src/features/VesselSidebar/Controls/Infraction.tsx
=> [Missions] Migration des champs d'infractions en bas du formulaire de contrôle

frontend/src/features/Healthcheck/components/HealthcheckHeadband.tsx, frontend/src/features/map/layers/DrawLayer.tsx, frontend/src/features/map/layers/InterestPointLayer.jsx, frontend/src/features/map/layers/MeasurementLayer.jsx, frontend/src/features/map/layers/RegulatoryLayerSearch.tsx, frontend/src/features/map/layers/RegulatoryLayers.tsx, frontend/src/features/map/layers/RegulatoryPreviewLayer.tsx, frontend/src/features/map/layers/styles/regulatoryLayer.style.ts, frontend/src/features/map/layers/styles/regulatoryPreview.style.jsx
- Resolve #2659
- Suppression des props `map` restantes
----
=>  [Cartographie] Réduire la transparence des couches REG

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission_actions/actrep/ActivityCode.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission_actions/actrep/species.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/MissionRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/GetActivityReports.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/dtos/ActivityReport.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/MissionActionsController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/ActivityReportDataOutput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaMissionActionsRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBMissionActionsRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/GetActivityReportsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/MissionActionsControllerITests.kt
=> [Tech] Lint Backend

backend/src/main/resources/db/migration/internal/V0.242__Update_database_permissions.sql
- Resolve #2800
Metabase est bien connecté à la base avec un user `metabase` auquel on a attribué le rôle `readaccess`, créé avec seulement les droits en lecture, mais par défaut tous les utilisateurs ont des droits étendus sur le schéma `public`. Mieux retirer ces droits par défaut et gérer explicitement les droits par user.
=> Révocation des droits en modification pour tous les utilisateurs sur le schéma `public`

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission_actions/actrep/JointDeploymentPlan.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission_actions/actrep/species.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/GetActivityReports.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/dtos/ActivityReport.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/dtos/ActivityReports.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/MissionActionsController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/ActivityReportDataOutput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/ActivityReportsDataOutput.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/GetActivityReportsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PublicMissionActionsControllerITests.kt, frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/cypress/e2e/side_window/mission_list/export_activity_reports.spec.ts, frontend/src/features/SideWindow/MissionList/ExportActivityReportsDialog/__tests__/utils.test.ts, frontend/src/features/SideWindow/MissionList/ExportActivityReportsDialog/apis.ts, frontend/src/features/SideWindow/MissionList/ExportActivityReportsDialog/constants.ts, frontend/src/features/SideWindow/MissionList/ExportActivityReportsDialog/types.ts, frontend/src/features/SideWindow/MissionList/ExportActivityReportsDialog/useCases/downloadActivityReports.ts, frontend/src/features/SideWindow/MissionList/ExportActivityReportsDialog/utils.ts
=> [WIP] Act Rep - Filtrage des espèces du JDP dans les colonnes du `csv`

frontend/src/App.tsx, frontend/tsconfig.json
- J'aurais pu mettre un `"@/*": ["*"],` mais je préfère être déclaratif pour ne garder que les paths qui correspondent à notre structure "officielle".
- La raison pour laquelle je n'ai pas mis les dossiers `auth/`, `context/`, `errors/` et `workers/` et que j'aimerais challenger leur emplacement actuel.
- MTES-MCT/monitorenv#1193
----
=> [Tech] Configure les paths dans tsconfig

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission_actions/actrep/JointDeploymentPlan.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission_actions/actrep/species.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/GetActivityReports.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission_actions/actrep/JointDeploymentPlanUTests.kt
=> [Act-Rep] Ajout des espèces soumises à quotas pour les navires tiers

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/vessel/Vessel.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/vessel/VesselUTests.kt
=> [Act-Rep] Afficher l'identifiant navire pour tous les pavillons 

.github/workflows/cicd.yml, frontend/src/domain/types/layer.ts, frontend/src/features/AdministrativeZone/layers/AdministrativeLayers.tsx, frontend/src/features/AdministrativeZone/layers/constants.ts, frontend/src/features/AdministrativeZone/layers/styles/administrativeLayer.style.ts, frontend/src/features/AdministrativeZone/layers/styles/geoserver_fao_style.md
=> [Zones FAO] Affichage des zones avec Geoserver

frontend/src/store/migrations.ts, frontend/src/store/reducers.ts
=> [Missions] Corrige l'erreur de local storage suite au renommage de clé des façade

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/PriorNotificationPdfDocumentRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/UpdatePriorNotificationNote.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/PriorNotificationPdfDocumentEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPriorNotificationPdfDocumentRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotificationUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/UpdatePriorNotificationNoteUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepositoryITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPriorNotificationPdfDocumentRepositoryITests.kt, frontend/cypress/e2e/side_window/prior_notification_card/card.spec.ts, frontend/cypress/e2e/side_window/prior_notification_form/form.spec.ts, frontend/src/api/types.ts, frontend/src/features/PriorNotification/components/PriorNotificationCard/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationForm/Card.tsx, frontend/src/features/PriorNotification/components/shared/DownloadButton/index.tsx, frontend/src/features/PriorNotification/priorNotificationApi.ts, frontend/src/features/PriorNotification/useCases/openPriorNotificationCard.ts, frontend/src/features/PriorNotification/useCases/updatePriorNotificationNote.ts, frontend/src/utils/normalizeRtkBaseQuery.ts
- Resolve #3374
- Resolve #3375
----
=> Préavis - Amélioration de la logique d'enregistrement, de téléchargement et de diffusion

frontend/src/api/api.ts
=> Cerbère - Ajout d'une condition `OIDC_ENABLED` pour envoyer le token `jwt`

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicPriorNotificationController.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PublicPriorNotificationControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicPriorNotificationControllerITests.kt, frontend/cypress/e2e/side_window/prior_notification_card/card.spec.ts, frontend/src/api/api.ts, frontend/src/features/PriorNotification/components/shared/DownloadButton/index.tsx, frontend/src/features/PriorNotification/priorNotificationApi.ts, frontend/src/features/PriorNotification/useCases/updatePriorNotificationNote.ts
- Car on ne peut pas sécuriser ce endpoint avec `window.open`.
- Pour éviter de bloquer l'activation de Cerbère
----
=> Préavis - Déplacement du endpoint  de téléchargement des PDF sur `/api`

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/LastPositionRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/VesselRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/reporting/GetAllCurrentReportings.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/cache/CaffeineConfiguration.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLastPositionRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaVesselRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBLastPositionRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBVesselRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/GetAllCurrentReportingsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLastPositionRepositoryITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaVesselRepositoryITests.kt
=> Optimisation des requêtes de l'application

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/fao_area/FAOArea.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fao_areas/GetFAOAreas.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/FAOAreasEntity.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/GetFAOAreasUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/UtilsUTests.kt
=> Zones FAO - Correction de la liste des zones

datascience/src/pipeline/flows/distribute_pnos.py, datascience/src/pipeline/flows/enrich_logbook.py, datascience/src/pipeline/queries/monitorfish/pno_species_and_gears.sql, datascience/src/pipeline/shared_tasks/pnos.py, datascience/tests/test_pipeline/conftest.py, datascience/tests/test_pipeline/test_flows/test_distribute_pnos.py, datascience/tests/test_pipeline/test_flows/test_enrich_logbook.py, datascience/tests/test_pipeline/test_shared_tasks/test_pnos.py
=> Diffusion des préavis auto [pipeline] - flaguer `isBeingSent` un préavis hors scope uniquement si des unités le ciblent

datascience/src/pipeline/flows/init_pno_types.py, datascience/src/pipeline/flows/missions.py, datascience/src/pipeline/generic_tasks.py, datascience/src/pipeline/utils.py, datascience/tests/test_pipeline/test_flows/test_missions.py
=> Utiliser `TRUNCATE` plutôt que `DELETE` pour vider une table avant de la mettre à jour

frontend/src/features/ActivityReport/__tests__/utils.test.ts, frontend/src/features/ActivityReport/utils.ts
=> Actrep - Ne pas faire apparaître la valeur "OTH" lorsqu'elle est égale à "0" lors des extractions

frontend/src/features/Logbook/LogbookMessage.types.ts, frontend/src/features/PriorNotification/components/LogbookPriorNotificationForm/Form.tsx, frontend/src/features/PriorNotification/components/LogbookPriorNotificationForm/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/index.tsx, frontend/src/features/PriorNotification/components/shared/DownloadButton/__tests__/getHtmlContent.test.ts, frontend/src/features/PriorNotification/constants.ts, frontend/src/features/PriorNotification/useCases/openPriorNotificationCard.ts
- Le champ note des préavis n'est pas visible dans la partie `ext`
----
=> Préavis - Afficher le champ note dans la partie `ext`

frontend/src/api/alert.ts
- Le header n'était pas envoyé lors de la mise sous silence des alertes
----
=> Tech - Envoi d'un header JWT manquant

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/Utils.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/prior_notification/PriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/VesselRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetNumberToVerify.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotifications.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/utils/PaginatedList.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/LogbookReportEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaVesselRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBVesselRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetNumberToVerifyUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaVesselRepositoryITests.kt
=> Préavis - Amélioration de la vitesse de la liste des PNOs

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetVesselVoyage.kt, frontend/src/features/PriorNotification/PriorNotification.types.ts
- Resolve #3262
- Resolve #3265
----
=> Afficher les messages JPE déclarés jusqu'à 4h dans le futur 

Makefile, backend/scripts/test-watch.sh, datascience/docs/source/contributing.rst
=> Tech - Ajoute quelques commandes au Makefile

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/MissionAction.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/PatchableMissionAction.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/input/PatchableMissionActionDataInput.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/mission_actions/PatchMissionActionUTests.kt
La date de début d'une action est aussi censée être éditable par les unités terrain.
Dites moi si j'ai oublié des choses dans la PR
----
=> Contrôles - Modification de la date de début d'actions par RapportNav

frontend/src/features/PriorNotification/components/LogbookPriorNotificationForm/index.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/index.tsx, frontend/src/features/PriorNotification/components/shared/DownloadButton/index.tsx, frontend/src/features/PriorNotification/useCases/openLogbookPriorNotificationForm.ts, frontend/src/features/PriorNotification/useCases/openManualPriorNotificationForm.ts, frontend/src/libs/customSentry.ts
=> Préavis – Traque le temps d'affichage du spinner et de l'activation du bouton télécharger

datascience/src/pipeline/emails/templates/prior_notifications/email_body_template.jinja, datascience/tests/test_data/emails/prior_notifications/expected_email_body_1.html, frontend/cypress/e2e/side_window/logbook_prior_notification_form/form.spec.ts, frontend/cypress/e2e/side_window/prior_notification_list/filter_bar.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/PriorNotification/components/LogbookPriorNotificationForm/Form.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/Content.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/Form.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/FormikExtraField.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/FilterBar.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/Row.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/utils.ts, frontend/src/features/PriorNotification/components/shared/DownloadButton/index.tsx
=> Préavis – Correction de divers points restants

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreatePriorNotificationUpload.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/DeletePriorNotificationUpload.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotifications.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/PriorNotificationUploadDataOutput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/PriorNotificationUploadEntity.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationsITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationControllerUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPriorNotificationPdfDocumentRepositoryITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPriorNotificationUploadRepositoryITests.kt, frontend/cypress/e2e/side_window/prior_notification_list/filter_bar.spec.ts, frontend/src/features/Logbook/LogbookMessage.types.ts, frontend/src/features/PriorNotification/components/PriorNotificationList/FilterBar.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/FilterTags.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/constants.ts, frontend/src/features/PriorNotification/components/PriorNotificationList/types.ts, frontend/src/features/PriorNotification/components/PriorNotificationList/utils.ts
=> Préavis – Ajoute le statut 'Invalidé' et regroupe les états en attente dans le filtre des status de diffusion

frontend/src/features/PriorNotification/components/shared/DownloadButton/template.ts, frontend/src/features/PriorNotification/components/shared/DownloadButton/utils.tsx
=> Préavis – Problème avec la date de réception du préavis dans les pdf d'autorisation (navire tiers)

Makefile, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/reporting/GetVesselReportings.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/reporting/GetVesselReportingsUTests.kt, frontend/cypress/e2e/vessel_sidebar/reporting.spec.ts, frontend/src/features/Reporting/components/VesselReportings/ReportingCard.tsx
- Resolve #3188
- Resolve #3183
- #3594
- Ajout de documentation dans le Makefile:
----
=> Signalements - Retouches UI

frontend/src/features/LayersSidebar/components/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationListButton.tsx
=> Hotfix – Corrige les boutons du menu de gauche

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/ControlUnitRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/control_units/GetAllControlUnits.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/cache/CaffeineConfiguration.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/monitorenv/APIControlUnitRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/monitorenv/APIMissionRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/monitorenv/APIControlUnitRepositoryITests.kt
- Resolve #3594 
- Le cache ne gère pas les `Deferred`, il faut le gérer manuellement
----
=> Tech - Correction du cache des unités de contrôles

frontend/src/auth/hooks/useCustomAuth.tsx
=> Cerbère - Renouvelement du token lorsqu'il est déjà expiré

frontend/src/domain/entities/beaconMalfunction/constants.tsx, frontend/src/features/Mission/components/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/Infraction.tsx, frontend/src/features/Mission/components/MissionForm/ActionForm/shared/FormikSpeciesQuantitySeized.tsx, frontend/src/features/Mission/components/MissionForm/ActionForm/shared/VesselFleetSegmentsField.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/FilterBar.tsx, frontend/src/features/SideWindow/BeaconMalfunctionBoard/SendNotification.tsx
- Resolve #3691
- Resolve #3727
- Resolve #3724
- Resolve #3697
- 
----
=> Préavis & CR de contrôle - Améliorations

datascience/src/pipeline/queries/monitorfish/missing_deps.sql
- Resolve #3756
- On ne lève pas d'alerte quand le dernier DEP détecté (qui peut être celui de la veille, étant qu'on ne regarde que dans la fenêtre `[now - 48 hours, now - 2 hours]`) est **antérieur** au dernier DEP déclaré --> suppression du `ABS` dans la requête sur l'écart maximum entre le DEP déclaré et le DEP détecté.
- Quand le dernier DEP détecté est **postérieur** au dernier DEP déclaré, on augmente la tolérance de 3 à 6 heures sur l'écart max entre l'heure de départ déclarée et l'heure de départ détectée pour éviter de lever des alertes quand les navires partent plus tard que l'heure déclarée. Il faut rester bien en-deçà de 24 heures pour ne pas associer un DEP déclaré d'un jour avec un autre DEP détecté (mais non déclaré) le lendemain.
=> Evolution de l'alerte de DEP manquant pour éviter les faux positifs

frontend/src/features/PriorNotification/components/PriorNotificationList/index.tsx
=> Préavis - Limite la fréquence des appels API après changement de filtre dans la liste

datascience/src/pipeline/flows_config.py
- Resolve #3809
----
Analyse : des alertes de DEP manquant peuvent apparaître de façon transitoire sur un navire ayant émis un DEP en raison de synchronisations décalées de différentes données.
Situation actuelle sur les flows impliqués dans le calcul du champ `departure_datetime_utc` de la table `last_positions`, utilisé par l'alerte de DEP manquant :
- flow `current_segments` : synchronisation à 2, 22, 42 (minutes de chaque heure : 13:02, 13:22, 13:42, 14:02, 14:22...)
- flow `risk_fators` : synchronisation à 3, 23, 43
- flow `last_positions` : synchronisation chaque minute
- flow `missing_dep_alerts` : déclenchement à 1, 16, 31, 46
--> Ainsi un DEP émis par le navire à 12:45 sera synchronisé dans `current_segments` qu'à 13:02, puis dans `risk_factors` à 13:03, puis dans …
=> Mise à jour de la fréquence de déclenchement des alertes de DEP manquant pour éviter les fausses alertes

.github/workflows/cicd.yml
- Quand on pousse un nouveau commit sur une PR, ceci annule la github action en cours
----
=> Tech - Annulation des builds concurrents sur PR

frontend/src/auth/apis.ts, frontend/src/libs/FrontendError.ts
- Une erreur 401 est normale, car un token a une durée limitée, nous ne voulons pas log sur Sentry ce type d'erreur
----
=> Tech - Nettoie le flot d'erreurs d'auth sur Sentry

backend/src/main/resources/db/migration/internal/V0.284__Update_beacons_table.sql, datascience/src/pipeline/queries/fmc/beacons.sql, datascience/tests/test_pipeline/test_flows/test_beacons.py
- Resolve #1721
Vérifier en front que l'affichage est OK avec des `NULL` dans les champs :
- `vessel_id`
- `beacon_status`
- `logging_datetime_utc`
- `beacon_type`
- `is_coastal`
=> Récupérer toutes les balises de Poséidon, pas uniquement celles qui sont associées à un navire à l'instant T

backend/src/main/resources/db/migration/internal/V0.285__Create_pno_extra_subscriptions_table.sql, datascience/src/pipeline/entities/pnos.py, datascience/src/pipeline/flows/distribute_pnos.py, datascience/src/pipeline/queries/monitorfish/pno_extra_subscriptions.sql, datascience/tests/test_data/remote_database/V666.41__Reset_test_pno_extra_subscriptions.sql, datascience/tests/test_pipeline/test_entities/test_pnos.py, datascience/tests/test_pipeline/test_flows/test_distribute_pnos.py, datascience/tests/test_pipeline/test_flows/test_regulations_checkup.py
- Resolve #3894
- Ajout d'une table `pno_extra_subscriptions` qui permet d'ajouter des destinataires hors unités aux diffusions de PNO
- Chaque ligne de cette table comporte 
- un `locode` de port
- un `pno_type_name` (type de préavis)
- le nom du destinataire
- son  organisation
- le mode de communication (`SMS` / `EMAIL`)
- son email ou numéro de téléphone  
- Le flow `distribute_pnos` utilise ces abonnements pour assigner des destinataires supplémentaires, en plus des unités, aux préavis dont le port et le type de préavis correspondent à un abonnement
- Pour l'instant le besoin existant est de diffuser uniquement les préavis navires tiers à certains destinataires par email. Pour éviter de hard coder ceci j'ai préféré prévoir un système plus souple dans le quel on peut paramétrer des …
=> Diffusion des préavis à des destinataires hors unités

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/input/LogbookPriorNotificationFormDataInput.kt, frontend/cypress/e2e/side_window/logbook_prior_notification_form/behavior.spec.ts, frontend/cypress/e2e/side_window/logbook_prior_notification_form/form.spec.ts, frontend/cypress/e2e/side_window/manual_prior_notification_form/behavior.spec.ts, frontend/src/features/PriorNotification/components/LogbookPriorNotificationForm/Footer.tsx, frontend/src/features/PriorNotification/components/LogbookPriorNotificationForm/Form.tsx, frontend/src/features/PriorNotification/components/LogbookPriorNotificationForm/index.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/Content.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/Form.tsx, frontend/src/features/PriorNotification/components/PriorNotificationCard.tsx, frontend/src/features/PriorNotification/components/shared/utils.ts, frontend/src/features/PriorNotification/useCases/updateLogbookPriorNotification.ts
- Resolve #3589
- Resolve #3856
- Resolve #3750
----
=> Préavis – Passer les préavis auto en enregistrement manuel

frontend/cypress/e2e/favorite_vessel.spec.ts, frontend/cypress/e2e/main_window/vessel_sidebar/logbook.spec.ts, frontend/cypress/e2e/measurement.spec.ts, frontend/cypress/e2e/side_window/beacon_malfunction/board.spec.ts, frontend/cypress/e2e/sidebars/regulatory_layers.spec.ts, frontend/src/features/FleetSegment/useCases/computeFleetSegments.ts, frontend/src/features/Logbook/useCases/getVesselLogbook.ts, frontend/src/features/Mission/components/MissionForm/useCases/updateActionFAOAreas.ts, frontend/src/features/Reporting/components/ReportingCard/index.tsx, frontend/src/features/Reporting/components/ReportingTable/index.tsx, frontend/src/features/Reporting/useCases/deleteReporting.ts, frontend/src/hooks/useTableVirtualizer.ts
- Resolve #3784
- Correction : 
> Quand on navigue dans les marées et qu'on revient à la dernière, ça reste en trackDepth=CUSTOM et ça s'arrête au dernier message au lieu d'allez jusqu'à NOW
- Correction : forçage du `refetch` pour le calcul des segments et fao dans le CR de contrôle
- Correction : du `useTableVirtualizer`
----
=> Signalements – Pouvoir supprimer un signalement archivé

datascience/src/pipeline/helpers/emails.py, datascience/tests/test_pipeline/test_helpers/test_emails.py
=> Ajout d'un en-tête manquant de `Date` aux emails générés par la pipeline (résolution de certains emails non reçus)

datascience/src/pipeline/flows/missing_dep_alerts.py, datascience/src/pipeline/shared_tasks/healthcheck.py, datascience/tests/test_pipeline/test_flows/test_missing_dep_alerts.py, datascience/tests/test_pipeline/test_shared_tasks/test_healthcheck.py
=> Stopper la génération d'alertes de DEP manquant pendant les pannes JPE

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicPortController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/VesselController.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicPortControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicVesselControllerITests.kt
Ajouté dans `public_api` des controllers pour les Ports et les Vessel (just l'endpoint /search)
----
=> APIs publiques - Ajout des APIs `/ports` et `/vessels/search`

frontend/src/store/index.ts, frontend/src/store/reducers.ts
- Le sotckage dans le `localstorage` ne permettait pas d'avoir la vue à date des dernières modifications.
----
=> Tech - Suppression du stockage des couches REG dans le backoffice

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/ComputeFleetSegments.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/ComputeFleetSegmentsFromControl.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputeManualPriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/FleetSegmentController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/input/ComputeFleetSegmentsDataInput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/input/ManualPriorNotificationComputeDataInput.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/ComputeFleetSegmentsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotificationITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotificationUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/FleetSegmentControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationControllerUTests.kt, frontend/cypress/e2e/side_window/manual_prior_notification_form/form.spec.ts, frontend/cypress/e2e/side_window/mission_form/sea_control.spec.ts, frontend/cypress/e2e/side_window/mission_form/sea_control_edition.spec.ts, frontend/src/features/FleetSegment/apis.ts, frontend/src/features/FleetSegment/useCases/computeFleetSegments.ts, frontend/src/features/Mission/components/MissionForm/ActionForm/shared/DatePickerField.tsx, frontend/src/features/Mission/components/MissionForm/hooks/useGetMissionActionFormikUsecases.ts, frontend/src/features/Mission/components/MissionForm/useCases/updateActionSegments.ts, frontend/src/features/PriorNotification/PriorNotification.types.ts, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/Content.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/utils.tsx
=> CR de contrôle - Lors du calcul du segment, ajouter la date du contrôle pour prendre en compte la bonne année du référentiel segments

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/SecurityConfig.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/ControllersExceptionHandler.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/SentryController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/SpaController.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/SpaControllerUTests.kt, frontend/src/api/api.ts, frontend/src/auth/utils.ts
- Do not retry on 401 http responses 
- Fix whitelabel error page error in API
- Prevent errors to be sent as duplicate to sentry
----
=> Tech - Corrections techniques SSO, erreurs APIs & `sentry`

frontend/.eslintrc.cjs, frontend/src/features/Draw/components/DrawModal.tsx, frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/messages/FARMessage/Haul.tsx, frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/messages/LogbookMessage.tsx, frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/messages/common/CatchDetails.tsx, frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/messages/common/SpecyCatch.tsx, frontend/src/features/Mission/components/MissionForm/ActionForm/shared/VesselField.tsx, frontend/src/features/Mission/components/MissionForm/ActionForm/shared/VesselFleetSegmentsField.tsx, frontend/src/features/Mission/components/MissionForm/MainForm/FormikLocationPicker.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/index.tsx, frontend/src/features/PriorNotification/components/shared/CardBodyHead/index.tsx, frontend/src/features/PriorNotification/components/shared/CardHeader.tsx, frontend/src/features/Vessel/components/VesselSidebar/Controls/Control.tsx, frontend/src/features/Vessel/components/VesselSidebar/Controls/Infraction.tsx, frontend/src/features/Vessel/components/VesselSidebar/Controls/LastControl.tsx, frontend/src/features/Vessel/components/VesselSidebar/Controls/YearControls.tsx, frontend/src/features/Vessel/components/VesselSidebar/Controls/YearsToControlList.tsx, frontend/src/features/Vessel/components/VesselSidebar/Equipment/resume/YearBeaconMalfunctions.tsx, frontend/src/features/Vessel/components/VesselSidebar/Equipment/resume/YearsToBeaconMalfunctionList.tsx, frontend/src/features/Vessel/components/VesselSidebar/VesselSidebarHeader/VesselName.tsx, frontend/src/features/Vessel/components/VesselSidebar/actions/TrackRequest/ExportTrack.tsx, frontend/src/features/Vessel/components/VesselSidebar/actions/TrackRequest/TrackDepthSelection.tsx, frontend/src/features/Vessel/components/VesselSidebar/actions/TrackRequest/index.tsx, frontend/src/features/Vessel/components/VesselSidebar/actions/show_fishing_activities/index.tsx, frontend/src/hooks/useForceUpdate.ts
- Resolve #4035
- Corrections de re-render de la side-window avec un `forceRender`:
- Dans la liste des destinataires du PNO
- Lors du chargement de la liste des PNOs
- Suppression de `useMemo` et `useCallback` inutiles
- Resolve #4086
-  Resolve #4085
- https://github.com/MTES-MCT/monitor-ui/pull/1572 
----
=> Préavis - Afficher la fiche navire depuis le fiche préavis & modification des coordonnées d'un contrôle

frontend/cypress/e2e/side_window/manual_prior_notification_form/behavior.spec.ts, frontend/cypress/e2e/side_window/manual_prior_notification_form/form.spec.ts, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/FormikExtraField.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/FormikMainField.tsx
=> Préavis - Les données de captures dans les préavis manuels BFT sont incohérentes

datascience/src/pipeline/flows/position_alerts.py, datascience/src/pipeline/flows_config.py, datascience/tests/test_pipeline/test_flows_config.py
- Résout le bug qui apparait au moment du `register` sur le flow de `position_alerts` quand le paramètre `zones` est `None`.
- Ajoute un test sur la serialization / deserialisation des flows pour détecter ce genre de pb avant MEP.
=> Fiabilisation de la planification des `flows`

datascience/src/pipeline/flows_config.py
- Les alertes "lingue bleue" ne doivent se déclencher que de mars à mai
- Modification des heures de déclenchement pour éviter les conflits entre les différents runs du flow `position_alerts`
=> Mise à jour de la chronicité des alertes lingue bleue et NEAFC

datascience/src/pipeline/parsers/ers/log_parsers.py
- Resolve #4199
----
```SQL
UPDATE logbook_reports
SET activity_datetime_utc = (value->>'predictedArrivalDatetimeUtc')::TIMESTAMPTZ AT TIME ZONE 'UTC'
WHERE log_type = 'PNO' AND transmission_format = 'ERS'
```
=> Fix pno ERS parser

backend/src/main/resources/db/migration/internal/V0.296__Update_positions_table.sql, backend/src/main/resources/db/migration/internal/V0.298__Update_positions_table.sql
Pour éviter le down della muerte.
Faire tourner enrich_positions ensuite.
=> Modification de la migration de `positions`

datascience/src/pipeline/flows/enrich_logbook.py, datascience/src/pipeline/queries/monitorfish/pno_catches.sql, datascience/tests/test_pipeline/test_flows/test_enrich_logbook.py
- Resolve #4269
Plantage dû à un échec de la jointure DuckDB dans `enrich_logbook` > `compute_pno_segments` sur la clef `facade`, en raison d'un mismatch de type (en absence de donnée, pandas convertit la colonne en `float`).
Corrigé en remplaçant les NULL par la value 'Hors façade' en cas de port inconnu ou avec une façade NULL.
=> Correction d'un bug dans l'enrichissement des préavis

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetVessels.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/VesselController.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetVesselsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicVesselControllerITests.kt
Ajout d'un endpoint pour avoir accès à tous les Vessels. 
A la base, le /search nous suffisait mais vu qu'on bosse sur le offline, il faut que l'on pré-download les référentiels statiques côté frontend, d'où la nécessité de cet endpoint pour RapportNav
----
=> APIs - Ajout d'une API publique pour récupérer tous les navires

datascience/src/pipeline/queries/ocan/eu_vessels.sql
- Car navire sans licence FR (donc statut RET sur NAVPRO)
----
=> Navires - Ajout d'un navire inactif `GB`

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/prior_notification/ManualPriorNotificationComputedValues.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/ReportingRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputeManualPriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/SelectedVesselDataOutput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaReportingRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBReportingRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputeManualPriorNotificationUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotificationITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotificationUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationControllerUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaReportingRepositoryITests.kt, datascience/src/pipeline/flows/enrich_logbook.py, datascience/src/pipeline/queries/monitorfish/active_reportings.sql, datascience/src/pipeline/queries/monitorfish/non_archived_reportings_of_type.sql, datascience/src/pipeline/queries/monitorfish/vessels_with_active_reportings.sql, datascience/src/pipeline/queries/monitorfish/vessels_with_active_reportings_for_pnos.sql, datascience/tests/test_data/remote_database/V666.20__Reset_test_reportings.sql, datascience/tests/test_pipeline/test_flows/test_enrich_logbook.py, datascience/tests/test_pipeline/test_flows/test_last_positions.py, datascience/tests/test_pipeline/test_shared_tasks/test_alerts.py
- Resolve #4237
A checker : faut-il inclure uniquement les navires avec des signalements de type `ALERT` et  `INFRACTION_SUSPICION` ?
=> Forcer la vérification des préavis de navires présentant un signalement actif

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepositoryITests.kt
=> JPE - Le LAN de la marée précédente fait sélectionner la mauvaise marée

frontend/src/features/BeaconMalfunction/components/BeaconMalfunctionBoard/VesselStatusSelect.tsx, frontend/src/features/BeaconMalfunction/components/BeaconMalfunctionBoard/index.tsx, frontend/src/features/Regulation/components/RegulationForm/FishingPeriod/index.tsx, frontend/src/features/Regulation/components/RegulationForm/GearRegulation/RegulatedGear.tsx, frontend/src/features/Regulation/components/RegulationForm/GearRegulation/RegulatedGears.tsx, frontend/src/features/Regulation/components/RegulationForm/GearRegulation/index.tsx, frontend/src/features/Regulation/components/RegulationForm/index.tsx, frontend/src/features/Regulation/components/RegulationForm/species_regulation/RegulatedSpecies.tsx, frontend/src/features/Regulation/components/RegulationForm/species_regulation/SpeciesRegulation.tsx, frontend/src/ui/LegacyRsuiteComponentsWrapper.tsx
=> UI - Retours design suite aux changements de composants

infra/prefect_3_server/docker-compose.yml, pipeline/src/deployments.py
- Tous les flows déployés sont mis en pause
- Ajout d'une restart policy sur Redis
- Mise à jour de la config de concurrency sur les alertes de position
=> Déploiement partiel Prefect 3
