MTES-MCT/monitorfish

.github/workflows/cicd-data-processing.yml, infra/remote/data-pipeline/int/start-flows.sh, infra/remote/data-pipeline/int/start-server.sh, infra/remote/data-pipeline/prod/start-flows.sh, infra/remote/data-pipeline/prod/start-server.sh
=> Run data pipeline services in detached mode

frontend/package-lock.json, frontend/package.json, frontend/src/components/fishing_activities/FishingActivitiesSummary.js, frontend/src/components/fishing_activities/ers_messages/ERSMessage.js, frontend/src/components/fishing_activities/ers_messages/FARMessage.js, frontend/src/components/fishing_activities/ers_messages/index.js, frontend/src/components/regulatory_zones/RegulatoryZoneMetadata.js, frontend/src/domain/entities/ERS.js, frontend/yarn.lock
Issues Fixed :
- [#200] 
- [#272]
- [#63]
=> Fix varius issues

frontend/src/api/APIWorker.js, frontend/src/components/controls/Control.js, frontend/src/components/controls/ControlField.js, frontend/src/components/controls/LastControlZone.js, frontend/src/utils.js
... and upgrade refresh of map to 2 minutes, because of bandwidth issue
=> Fix lat/long formatting and margin of last controls boxes

frontend/src/components/administratives_zones/AdministrativeZoneGroup.js, frontend/src/components/administratives_zones/AdministrativeZones.js, frontend/src/components/base_layers/BaseLayerItem.js, frontend/src/components/base_layers/BaseLayerSelection.js, frontend/src/components/regulatory_zones/RegulatoryZoneMetadata.js, frontend/src/components/regulatory_zones/RegulatoryZoneSelected.js, frontend/src/components/regulatory_zones/RegulatoryZoneSelectedLayer.js, frontend/src/components/regulatory_zones/RegulatoryZoneSelectedZone.js, frontend/src/components/regulatory_zones/RegulatoryZoneSelection.js, frontend/src/components/regulatory_zones/RegulatoryZoneSelectionItem.js, frontend/src/components/regulatory_zones/RegulatoryZoneSelectionList.js, frontend/src/components/regulatory_zones/RegulatoryZoneSelectionSearchInput.js, frontend/src/containers/LayersSidebar.js, frontend/src/containers/VesselList.js, frontend/src/domain/use_cases/getAdministrativeZonesAndSubZones.js
J'ai enlevé les `props` qui descendaient des `containers` dans le composant `LayersSidebar`
=> Refactored layers sidebar and fix #413

frontend/src/App.css, frontend/src/components/icons/Bouton_exporter_piste_navire.svg, frontend/src/components/icons/Icone_navire_noir.svg, frontend/src/components/track_depth_selection/TrackDepthDateRange.js, frontend/src/components/track_depth_selection/TrackDepthRadio.js, frontend/src/components/track_depth_selection/TrackDepthSelection.js, frontend/src/components/track_depth_selection/TrackPositionsTable.js, frontend/src/components/track_export/TrackExport.js, frontend/src/components/vessel_list/VesselListTable.js, frontend/src/components/vessel_list/tableSort.js, frontend/src/domain/reducers/Vessel.js, frontend/src/layers/VesselTrackLayer.js, frontend/src/layers/styles/featuresStyles.js
Affiche la liste des positions en dessous du paramétrage de la longuer de la piste navire
=> Show positions af the selected vessel track

datascience/src/pipeline/queries/monitorfish/last_positions.sql
=> Remove positions in the future from last_positions table

frontend/src/components/backoffice/LawType.js, frontend/src/components/commonStyles/Buttons.style.js, frontend/src/components/regulatory_zones/RegulatoryZoneSelectedLayer.js, frontend/src/components/regulatory_zones/RegulatoryZoneSelectedZone.js, frontend/src/containers/Backoffice.js, frontend/src/domain/reducers/Regulatory.js
Traitement des retours de @AdelineCelier sur [285](https://github.com/MTES-MCT/monitorfish/issues/285)
=> Fix backoffice ux/ui

frontend/src/components/overlays/VesselEstimatedPositionCardOverlay.js, frontend/src/domain/entities/estimatedPosition.js, frontend/src/layers/VesselEstimatedPositionLayer.js, frontend/src/layers/styles/vessel.style.js, frontend/src/layers/styles/vesselEstimatedPosition.style.js
- Add estimated position circle feature
- Fix caching of styles
=> Add estimated position circle feature

frontend/src/components/fishing_activities/ers_messages/ERSMessage.js, frontend/src/components/fishing_activities/ers_messages/ERSMessageSpecies.js, frontend/src/components/track_depth_selection/TrackPositionsTable.js
=> Fix #438 and #451 bugs

frontend/src/components/backoffice/LawType.js, frontend/src/components/backoffice/SearchRegulations.js, frontend/src/components/commonStyles/Text.style.js, frontend/src/components/regulatory_zones/RegulatoryZoneSelectedLayer.js, frontend/src/containers/Backoffice.js, frontend/src/fonts/fonts.js
- [#437](https://github.com/MTES-MCT/monitorfish/issues/437) 
- [#285](https://github.com/MTES-MCT/monitorfish/issues/285)
=> Fix #437 and #285 issues

datascience/src/pipeline/flows/fishing_gear_codes.py
=> Split seine nets fishing gears into 2 categories

frontend/src/constants/constants.js, frontend/src/domain/use_cases/hideLayer.js, frontend/src/features/commonStyles/icons/CloseIcon.style.js, frontend/src/features/coordinates/DMSCoordinatesInput.js, frontend/src/features/icons/Bouton_edition.svg, frontend/src/features/icons/Loupe_dark.svg, frontend/src/features/icons/Point_interet_autre.svg, frontend/src/features/icons/Suppression.svg, frontend/src/features/icons/reg_paper.svg, frontend/src/features/interest_points/SaveInterestPoint.js, frontend/src/features/layers/LayersSidebar.js, frontend/src/features/layers/administrative/AdministrativeLayer.js, frontend/src/features/layers/administrative/AdministrativeLayerGroup.js, frontend/src/features/layers/administrative/AdministrativeLayers.js, frontend/src/features/layers/base/BaseLayers.js, frontend/src/features/layers/regulatory/RegulatoryLayerTopic.js, frontend/src/features/layers/regulatory/RegulatoryLayerZone.js, frontend/src/features/layers/regulatory/RegulatoryLayerZoneMetadata.js, frontend/src/features/layers/regulatory/RegulatoryLayers.js, frontend/src/features/layers/regulatory/search/RegulatoryLayerSearchInput.js, frontend/src/features/layers/regulatory/search/RegulatoryLayerSearchResultList.js, frontend/src/features/layers/regulatory/search/RegulatoryLayerSearchResultTopic.js, frontend/src/features/layers/regulatory/search/RegulatoryLayerSearchResultZone.js, frontend/src/features/map/overlays/InterestPointOverlay.js
Fixes:
- https://github.com/MTES-MCT/monitorfish/issues/278#issuecomment-906503434
- https://github.com/MTES-MCT/monitorfish/issues/435#issuecomment-907012918
=> 278 435 UI feedbacks

frontend/src/api/APIWorker.js, frontend/src/domain/use_cases/showVesselTrackAndSidebar.js, frontend/src/features/vessel_sidebar/track_depth_selection/TrackDepthSelection.js
- Fixes #548 
- Augmente la MAJ des navires à 10 minutes
=> Keep custom track depth when refresh

frontend/src/App.css, frontend/src/features/commonStyles/icons/VesselListSVG.js, frontend/src/features/controls/ControlsResumeZone.js, frontend/src/features/coordinates/DDCoordinatesInput.js, frontend/src/features/coordinates/DMDCoordinatesInput.js, frontend/src/features/coordinates/DMSCoordinatesInput.js, frontend/src/features/interest_points/InterestPoint.js, frontend/src/features/interest_points/SaveInterestPoint.js, frontend/src/features/vessel_list/VesselList.js, frontend/src/features/vessel_visibility/VesselVisibility.js, frontend/src/index.css, frontend/src/layers/InterestPointLayer.js
- resolve #282 
- resolve #278
=> Fix multiples issues

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/Position.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/mappers/NAFMessageMapper.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/PositionDataOutput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/VesselDataOutput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/PositionEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBPositionRepository.kt, backend/src/main/resources/db/migration/internal/V0.47__Update_positions_table.sql, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/GetVesselUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/BffControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPositionRepositoryITests.kt, frontend/src/features/icons/Pastille_position_manuelle.svg, frontend/src/features/interest_points/SaveInterestPoint.js, frontend/src/features/vessel_sidebar/track_depth_selection/TrackDepthSelection.js, frontend/src/features/vessel_sidebar/track_depth_selection/TrackPositionsTable.js, frontend/src/layers/InterestPointLayer.js
=> Add manual positions

frontend/src/domain/entities/estimatedPosition.js, frontend/src/domain/entities/fishingActivities.js, frontend/src/domain/entities/vessel.js, frontend/src/domain/shared_slices/Vessel.js, frontend/src/features/icons/Bouton_masquer_pistes_actif.svg, frontend/src/features/icons/Bouton_masquer_pistes_inactif.svg, frontend/src/features/interest_points/SaveInterestPoint.js, frontend/src/features/vessel_sidebar/VesselSidebar.js, frontend/src/features/vessel_sidebar/hide_other_vessels/HideOtherVessels.js, frontend/src/features/vessel_sidebar/track_depth_selection/TrackDepthSelection.js, frontend/src/features/vessel_sidebar/track_export/TrackExport.js, frontend/src/layers/InterestPointLayer.js, frontend/src/layers/VesselEstimatedPositionLayer.js, frontend/src/layers/VesselsLabelsLayer.js, frontend/src/layers/VesselsLayer.js, frontend/src/layers/styles/vessel.style.js, frontend/src/layers/styles/vesselEstimatedPosition.style.js
=> Add hide other vessels on layers

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/GetVessel.kt
=> Substract 4h to the departure date

frontend/cypress/integration/vessel_sidebar.spec.js, frontend/cypress/integration/vessel_track.spec.js, frontend/src/features/fishing_activities/ers_messages_resumes/LANMessageResume.js, frontend/src/features/map/cards/VesselCard.js, frontend/src/features/map/cards/VesselTrackCard.js, frontend/src/features/map/overlays/TrackTypeCardOverlay.js
Resolve #571 
- Update vessel sidebar test
- Add new vessel card and track card tests
=> Add new cypress tests

frontend/src/features/backoffice/create_regulation/NewRegulation.js, frontend/src/features/backoffice/create_regulation/RegulationRegionLine.js
[Description]
La ligne permettant de sélectionner un tracé n'était plus présente dans la page de création d'une réglementation.
La section a été ajoutée.
----
=> Add Geometry line

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/RiskFactorsEntity.kt, backend/src/main/resources/db/testdata/V666.11__Insert_risk_factors.sql
=> Handle NULL infraction_score

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/mappers/NAFMessageMapper.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/RiskFactorsEntity.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/mappers/NAFMessageMapperUTests.kt
=> Fix null infraction rate

frontend/cypress/plugins/index.js, frontend/cypress/support/index.js, frontend/package-lock.json, frontend/package.json, frontend/src/domain/shared_slices/Layer.js, frontend/src/domain/shared_slices/Regulatory.js, frontend/src/domain/use_cases/hideLayer.js, frontend/src/domain/use_cases/showRegulatoryLayer.js, frontend/src/features/map/BaseMap.js, frontend/src/features/map/Map.js, frontend/src/layers/RegulatoryLayers.js, frontend/src/layers/VesselsLabelsLayer.js, frontend/src/layers/styles/vectorLayer.style.js, frontend/src/types/layer.js
Simplifie la géometry affichée quand on dézoom à moins de 9.5 pour améliorer les performances
=> Add geometry simplify in front when dezooming

infra/remote/data-pipeline/int/start-flows.sh, infra/remote/data-pipeline/prod/start-flows.sh
=> Add restart policy to flows container

backend/src/main/resources/db/migration/internal/V0.70__Update_ers_table.sql
=> Add indexes on ers table

datascience/src/pipeline/processing.py, datascience/tests/test_pipeline/test_processing.py
=> Support all NULLS timedelta series inserts

frontend/src/features/vessel_list/VesselListTable.js, frontend/src/features/vessel_list/tableSort.js, frontend/src/layers/InterestPointLayer.js, frontend/src/layers/MeasurementLayer.js, frontend/src/layers/styles/measurement.style.js
- Ajout style sur outil de mesure #359
- Fix icone remplacée par texte pour en tête tableau Navires #661 
- Fix sort sur colonnes non numériques #752 
- Resolve #661
- Resolve #752 
- Resolve #359
----
=> Frontend - Fix measurement style vessels table sort

datascience/src/pipeline/flows/ers.py, datascience/src/pipeline/flows/last_positions.py, datascience/src/pipeline/shared_tasks/control_flow.py
=> Run flow unless running

frontend/src/features/vessel_sidebar/controls/Control.js
=> Fix control detail width

datascience/src/pipeline/schedules.py
- Resolve #767
----
Permet de supprimer dans Monitorfish les contrôles supprimés dans Poséidon a posteriori.
=> Sync all controls data once a day

frontend/src/domain/entities/layers.js, frontend/src/features/layers/regulatory/RegulatoryLayerTopic.js, frontend/src/features/layers/regulatory/search/RegulatoryLayerSearchResultZone.js, frontend/src/features/map/controls/LayerDetailsBox.js, frontend/src/layers/RegulatoryPreviewLayer.js, frontend/src/layers/styles/administrativeAndRegulatoryLayers.style.js, frontend/src/layers/styles/regulatoryPreview.style.js
=> Modify default regulatory layer color

frontend/src/domain/entities/fishingActivities.js, frontend/src/domain/shared_slices/FishingActivities.js, frontend/src/features/vessel_sidebar/fishing_activities/ers_messages/ERSMessage.js
=> Handle DIM message type

frontend/cypress/integration/interest_point.spec.js, frontend/src/features/interest_points/SaveInterestPoint.js
=> Fix interest point type update

datascience/src/pipeline/flows/fao_areas.py
=> Remove fao_areas 'None' strings and fix encoding

frontend/src/features/vessel_list/DownloadVesselListModal.js
Resolve #602
[Description]
----
=> Frontend - export mmsi by default

frontend/cypress/integration/vessel_filters.spec.js, frontend/cypress/integration/vessel_track.spec.js, frontend/cypress/integration/vessel_visibility.spec.js, frontend/src/domain/shared_slices/Global.js, frontend/src/features/commonComponents/MapPropertyTrigger.js, frontend/src/features/vessel_filters/FilterParameters.js, frontend/src/features/vessel_filters/HideNonFilteredVessels.js, frontend/src/features/vessel_filters/VesselFilters.js, frontend/src/features/vessel_list/VesselList.js
=> Add shortcut to add a filter

datascience/src/pipeline/processing.py, datascience/src/pipeline/queries/monitorfish/compute_last_positions.sql, datascience/tests/test_pipeline/test_processing.py
=> Fix last positions flow

datascience/src/pipeline/flows/regulations.py
=> Specify jsonb columns in loading step of regulations flow

datascience/src/pipeline/flows/last_positions.py, datascience/src/pipeline/shared_tasks/control_flow.py
=> Disable prefect task checkpointing

frontend/cypress/integration/backoffice_new_regulation.spec.js, frontend/cypress/integration/backoffice_regulatory_zone_list.spec.js, frontend/cypress/integration/backoffice_update_regulation.spec.js, frontend/src/domain/entities/regulatory.js, frontend/src/domain/shared_slices/Regulatory.js, frontend/src/features/backoffice/Backoffice.js, frontend/src/features/backoffice/LawType.js, frontend/src/features/backoffice/LayerNameInput.js, frontend/src/features/backoffice/Regulation.slice.js, frontend/src/features/backoffice/SearchRegulations.js, frontend/src/features/backoffice/SectionTitle.js, frontend/src/features/backoffice/create_regulation/ConfirmRegulationModal.js, frontend/src/features/backoffice/create_regulation/NewRegulation.js, frontend/src/features/backoffice/create_regulation/custom_form/CustomDatePicker.js, frontend/src/features/backoffice/create_regulation/custom_form/CustomSelectComponent.js, frontend/src/features/backoffice/create_regulation/fishing_period/FishingPeriodForm.js, frontend/src/features/backoffice/create_regulation/fishing_period/FishingPeriodSection.js, frontend/src/features/backoffice/create_regulation/fishing_period/TimeInterval.js, frontend/src/features/backoffice/create_regulation/regulatory_identification/RegulationGeometryLine.js, frontend/src/features/backoffice/create_regulation/regulatory_identification/RegulationLawTypeLine.js, frontend/src/features/backoffice/create_regulation/regulatory_identification/RegulationRegionLine.js, frontend/src/features/backoffice/create_regulation/regulatory_identification/RegulationTopicLine.js, frontend/src/features/backoffice/create_regulation/regulatory_species/RegulatorySpeciesForm.js, frontend/src/features/backoffice/create_regulation/regulatory_text/RegulatoryText.js, frontend/src/features/backoffice/menu/Menu.js, frontend/src/features/commonStyles/Backoffice.style.js, frontend/src/features/commonStyles/Buttons.style.js, frontend/src/features/layers/regulatory/RegulatoryLayerTopic.js, frontend/src/features/layers/regulatory/RegulatoryLayerZone.js
[Description]
- #788 
- #715 
- #840 
- #845
- #868 
- #871 
----
=> Backoffice enhancement

datascience/src/pipeline/queries/monitorfish/compute_last_positions.sql
=> Fix last_positions query

frontend/src/features/backoffice/Backoffice.js
[Description]
- Resolve #895 
----
=> Add zoom handling in backoffice map

backend/src/main/resources/db/migration/layers/V0.101__Delete_facade_areas_table copy.sql, backend/src/main/resources/db/migration/layers/V0.102__Create_facade_areas_subdivided_table.sql, datascience/src/pipeline/flows/facade_areas.py, datascience/src/pipeline/queries/cross/facade_areas.sql, datascience/src/pipeline/queries/monitorfish/compute_ports_facade.sql, datascience/src/pipeline/queries/monitorfish/facade_areas.sql, datascience/src/pipeline/shared_tasks/facades.py
=> Subdivide facade_areas table

frontend/src/domain/entities/regulatory.js, frontend/src/features/backoffice/create_regulation/regulatory_gears/RegulatoryGearForm.js, frontend/src/features/backoffice/create_regulation/regulatory_gears/RegulatoryGearSection.js, frontend/src/features/backoffice/create_regulation/regulatory_identification/CreateRegulationTopicForm.js
[Description]
- Resolve #913 
----
=> Fix after review #913

frontend/.eslintrc.yml
new rules to ensure best practices
new rules are non blocking (warn)
relates to #886
=> Frontend - add rules to frontend linter

frontend/src/domain/entities/layers.js, frontend/src/features/map/Map.js, frontend/src/features/vessel_list/VesselList.js, frontend/src/features/vessel_list/VesselListFilters.js, frontend/src/layers/FilterLayer.js
=> 345 afficher zone filtre

frontend/src/api/APIWorker.js, frontend/src/domain/shared_slices/Vessel.js, frontend/src/features/map/MapMenu.js, frontend/src/features/vessel_list/VesselList.js, frontend/src/features/vessel_sidebar/actions/hide_non_selected_vessels/HideNonSelectedVessels.js, frontend/src/features/vessel_visibility/VesselVisibility.js, frontend/src/layers/VesselAlertLayer.js, frontend/src/layers/VesselEstimatedPositionLayer.js, frontend/src/layers/VesselsLabelsLayer.js, frontend/src/layers/VesselsLayer.js
Du coup j'ai réduit la temps de refresh des navires à 5 minutes au lieu de 10 minutes.
- Utiliser les ref en lazy, pour ne pas re-créer les objects à chaque render
- remove une event listener lors d'un unmount, qui contenait une grosse liste de navires
=> Fix memory leaks

frontend/cypress/integration/layers_sidebar.spec.js, frontend/package-lock.json, frontend/src/domain/entities/regulatory.js, frontend/src/domain/use_cases/showRegulatoryZoneMetadata.js, frontend/src/features/backoffice/Backoffice.js, frontend/src/features/backoffice/SearchRegulations.js, frontend/src/features/backoffice/create_regulation/InfoBox.js, frontend/src/features/backoffice/create_regulation/InfoPoint.js, frontend/src/features/backoffice/create_regulation/NewRegulation.js, frontend/src/features/backoffice/create_regulation/fishing_period/FishingPeriodForm.js, frontend/src/features/backoffice/create_regulation/regulatory_gears/RegulatoryGearForm.js, frontend/src/features/backoffice/create_regulation/regulatory_species/RegulatorySpeciesForm.js, frontend/src/features/backoffice/create_regulation/regulatory_text/RegulatoryText.js, frontend/src/features/backoffice/create_regulation/regulatory_text/UpcomingRegulationSection.js, frontend/src/features/commonStyles/Circle.style.js, frontend/src/features/layers/regulatory/RegulatoryLayerZone.js, frontend/src/features/layers/regulatory/RegulatoryLayerZoneMetadata.js, frontend/src/features/layers/regulatory/metadata/CodeAndName.js, frontend/src/features/layers/regulatory/metadata/GearsOrGearCategories.js, frontend/src/features/layers/regulatory/metadata/Identification.js, frontend/src/features/layers/regulatory/metadata/MetadataFishingPeriod.js, frontend/src/features/layers/regulatory/metadata/MetadataGears.js, frontend/src/features/layers/regulatory/metadata/MetadataRegulatoryReferences.js, frontend/src/features/layers/regulatory/metadata/MetadataSpecies.js, frontend/src/features/layers/regulatory/metadata/RegulatoryMetadata.style.js
[Description]
- Resolve #863
----
=> Update RegulatoryLayerZoneMetadata panel

datascience/src/pipeline/flows/position_alerts.py, datascience/tests/test_pipeline/test_flows/test_position_alerts.py
=> Update position alerts filter on gears

frontend/cypress/integration/vessel_search.spec.js, frontend/src/domain/shared_slices/Global.js, frontend/src/domain/use_cases/showVessel.js, frontend/src/features/vessel_search/VesselSearchList.js, frontend/src/features/vessel_search/VesselsSearch.js
=> Add last searched vessels on click

frontend/cypress/integration/vessel_track.spec.js, frontend/package-lock.json, frontend/src/domain/entities/vessel.js, frontend/src/domain/use_cases/showVessel.js, frontend/src/features/side_window/beacon_statuses/BeaconStatusCard.js, frontend/src/layers/VesselsLabelsLayer.js
=> Remove other properties from beacons or alerts to vessel identity object

frontend/cypress/integration/vessels_list.spec.js, frontend/src/features/vessel_list/DownloadVesselListModal.js
=> Fix coordinates format on vessel list export

frontend/src/domain/use_cases/getVesselVoyage.js, frontend/src/domain/use_cases/modifyVesselTrackDepth.js, frontend/src/domain/use_cases/showVessel.js, frontend/src/features/map/overlays/MapMenuOverlay.js, frontend/src/features/map/overlays/map_menu/CustomTrackDepthModal.js, frontend/src/features/vessel_sidebar/actions/track_depth_selection/TrackDepthDateRange.js, frontend/src/features/vessel_sidebar/actions/track_depth_selection/TrackDepthRadio.js, frontend/src/features/vessel_sidebar/actions/track_depth_selection/TrackDepthSelection.js, frontend/src/features/vessel_sidebar/fishing_activities/CustomDatesShowedInfo.js
=> Fix update of track depth

frontend/src/domain/use_cases/hideLayer.js, frontend/src/domain/use_cases/showAdministrativeLayer.js, frontend/src/domain/use_cases/showRegulatoryTopic.js, frontend/src/domain/use_cases/showRegulatoryZone.js, frontend/src/features/layers/regulatory/RegulatoryLayerTopic.js, frontend/src/features/layers/regulatory/RegulatoryLayerZone.js, frontend/src/features/layers/regulatory/RegulatoryLayers.js, frontend/src/layers/AdministrativeLayers.js, frontend/src/layers/RegulatoryLayers.js
=> Fix hide a single regulatory zone when a topic is shown

datascience/src/pipeline/queries/monitorfish/beacons_last_emission.sql
=> Only monitor beacons of French vessels

datascience/src/pipeline/flows/regulations.py, datascience/src/pipeline/queries/cross/regulations.sql
[Description]
- Resolve #1019
----
=> Add missing gears in regulations

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPositionRepository.kt
=> Add transactional decorator

datascience/src/pipeline/data/manually_added_ports.csv, datascience/src/pipeline/queries/monitorfish/compute_ports_facade.sql
=> Fix les galets port location

datascience/src/pipeline/data/fishing_gear_codes.csv
=> Update gears categories

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/GetVesselPositions.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/GetVesselPositionsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPositionRepositoryITests.kt, frontend/cypress/integration/vessel_sidebar.spec.js
=> Fix beacon number search not returning positions

.github/workflows/cicd.yml, backend/src/main/resources/db/migration/layers/V0.132__Create_effort_zones_areas_table.sql, backend/src/main/resources/db/migration/layers/V0.133__Create_neafc_regulatory_area_table.sql, datascience/src/pipeline/flows/admin_areas.py, datascience/src/pipeline/queries/cross/effort_zones_areas.sql, datascience/src/pipeline/queries/cross/neafc_regulatory_area.sql, frontend/src/domain/entities/layers.js, frontend/src/features/favorite_vessels/FavoriteVessels.js, frontend/src/features/map/overlays/MapMenuOverlay.js, frontend/src/layers/styles/administrativeAndRegulatoryLayers.style.js, infra/init/geoserver_init_layers.sh
=> Add two administrative zones

.github/workflows/cicd.yml
=> Add three jobs

frontend/src/features/backoffice/create_regulation/regulatory_gears/RegulatoryGearForm.js, frontend/src/features/layers/regulatory/metadata/GearsOrGearCategories.js
[Description]
- Resolve #1021
----
=> Do not show all gears by default

datascience/src/pipeline/flows/missing_trip_numbers.py, datascience/src/pipeline/queries/monitorfish/missing_trip_numbers.sql
=> Fix missing trip numbers

frontend/src/api/vessel.js
=> Vessel search encoding fix

datascience/config.py, datascience/src/pipeline/entities/monitorfish_healthcheck.py, datascience/src/pipeline/exceptions/__init__.py, datascience/src/pipeline/exceptions/monitorfish_health_error.py, datascience/src/pipeline/flows/update_beacon_malfunctions.py, datascience/src/pipeline/shared_tasks/healthcheck.py, datascience/tests/mocks.py, datascience/tests/test_pipeline/test_flows/test_update_beacon_malfunctions.py
=> Add last positions healthcheck in beacon malfunctions flow

backend/src/main/resources/db/migration/internal/V0.140__Create_analytics_controls_view.sql, backend/src/main/resources/db/migration/internal/V0.141__Create_analytics_facade_names_view.sql, backend/src/main/resources/db/migration/internal/V0.142__Create_analytics_fleet_segment_names.sql, backend/src/main/resources/db/migration/internal/V0.143__Create_analytics_control_types.sql
=> Create views for controls analytics

frontend/cypress/downloads/export_vms_16_05_2022_21.csv, frontend/cypress/integration/vessel_labels.spec.js, frontend/cypress/integration/vessels_list.spec.js, frontend/src/features/map/overlays/InterestPointOverlay.js, frontend/src/features/map/overlays/VesselLabelOverlay.js, frontend/src/features/vessel_list/DownloadVesselListModal.js, frontend/src/hooks/useMoveOverlayWhenDragging.js, frontend/src/layers/VesselsLabelsLayer.js
- Resolve #1168
- Resolve #1169
----
=> Fixes GDH export for Customs and open sidebar from vessel map label

frontend/src/utils.js, frontend/src/utils.test.js
=> Fix datetime display in front

frontend/src/features/side_window/alerts/PendingAlertsList.js, frontend/src/features/side_window/alerts/SilencedAlertsList.js
=> Extend table width when the scrollbar is showed on Windows

datascience/src/pipeline/flows/missing_far_alerts.py, datascience/tests/test_pipeline/test_flows/test_missing_far_alerts.py
=> Raise missing far alerts only for vessels at sea before 8pm

Makefile, infra/dev/README.md, infra/dev/docker-compose.dev.yml
No linked issue. No E2E tests required.
----
=> Add all-in-one run command in Makefile

frontend/cypress/integration/tritonfish.spec.js, frontend/src/App.js, frontend/src/features/vessel_list/VesselListTable.js
=> Add vessel list and filters to TritonFish

datascience/src/pipeline/data/species_groups.csv, frontend/cypress/integration/backoffice_new_regulation.spec.js, frontend/src/domain/entities/regulatory.js, frontend/src/features/backoffice/Backoffice.js, frontend/src/features/backoffice/constants.js, frontend/src/features/backoffice/edit_regulation/custom_form/CustomDatePicker.js
[Description]
- Various minor fixes for backoffice REG
- Resolve #1222
- Resolve #1223 
----
=> Add various fixes for backoffice REG

frontend/src/domain/use_cases/controller/getAllControllers.js, frontend/src/features/vessel_sidebar/reporting/current/NewReportingForm.js
=> Open reporting UI feedbacks

datascience/src/pipeline/flows_config.py
=> Update register for notify_beacon_malfunctions

frontend/src/features/vessel_sidebar/reporting/Reporting.js, frontend/src/features/vessel_sidebar/reporting/current/NewReportingForm.js
=> Add other UI fixes on new reporting

datascience/src/pipeline/flows/last_positions.py, datascience/src/pipeline/flows/missing_far_alerts.py, datascience/src/pipeline/flows/position_alerts.py, datascience/src/pipeline/flows/update_beacon_malfunctions.py, datascience/src/pipeline/processing.py, datascience/src/pipeline/queries/monitorfish/silenced_alerts.sql, datascience/src/pipeline/shared_tasks/alerts.py, datascience/tests/test_pipeline/test_flows/test_position_alerts.py, datascience/tests/test_pipeline/test_processing.py, datascience/tests/test_pipeline/test_shared_tasks/test_alerts.py
=> Fix bug of silenced alerts with multiple facades

datascience/src/pipeline/flows/last_positions.py, datascience/src/pipeline/processing.py, datascience/tests/test_pipeline/test_flows/test_last_positions.py, datascience/tests/test_pipeline/test_processing.py
=> Fix last positions update position

frontend/src/features/map/overlays/VesselLabelOverlay.js, frontend/src/features/side_window/alerts/PendingAlertsList.js, frontend/src/features/side_window/alerts/SilenceAlertMenu.js
=> Fix scroll positions in side window alerts

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/alerts/SilencedAlert.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/SilencedAlertRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/alert/GetSilencedAlerts.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/alert/SilenceOperationalAlert.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/alert/ValidateOperationalAlert.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/SilencedAlertEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaSilencedAlertRepository.kt, backend/src/main/resources/db/migration/internal/V0.152__Update_silenced_alerts_table.sql, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/GetSilencedAlertsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/SilenceOperationalAlertUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/ValidateOperationalAlertUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaSilencedAlertRepositoryITests.kt, frontend/cypress/integration/side_window_alerts.spec.js
=> Do not show validated alerts in silenced alerts

datascience/src/pipeline/flows/admin_areas.py, datascience/src/pipeline/queries/cross/saltwater_limit_areas.sql, datascience/src/pipeline/queries/cross/transversal_sea_limit_areas.sql, frontend/src/domain/entities/layers.js, frontend/src/layers/BaseLayer.js, frontend/src/layers/styles/administrativeAndRegulatoryLayers.style.js, infra/init/geoserver_init_layers.sh
- Resolve #1248 
- Resolve #1246 
----
=> Add two administrative zones and scan littoral base layer

backend/src/main/resources/db/migration/layers/V0.153__Create_saltwater_limit_areas_table.sql, backend/src/main/resources/db/migration/layers/V0.154__Create_transversal_sea_limit_areas_table.sql
=> Add admin tables DDL

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/logbook/EffortTargetSpeciesGroup.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/alert/rules/ExecutePnoAndLanWeightToleranceRule.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetLogbookMessages.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt, backend/src/main/resources/db/testdata/V666.5__Insert_logbook.sql, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/GetLogbookMessagesUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/TestUtils.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/alert/rules/ExecutePnoAndLanWeightToleranceRuleUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/VesselControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepositoryITests.kt, frontend/cypress/e2e/vessel_sidebar_control_buttons.spec.js, frontend/cypress/e2e/vessel_sidebar_fishing.spec.js, frontend/src/features/map/BaseMap.js, frontend/src/features/map/overlays/CloseVesselTrackOverlay.js, frontend/src/features/map/overlays/VesselLabelOverlay.js
- Resolve #1195
- Resolve #691 
- Resolve #957 
- Resolve #1138
- Resolve #867
----
=> fix: Multiple fixes

frontend/src/api/APIWorker.js, frontend/src/features/side_window/alerts/PendingAlertRow.js, frontend/src/features/side_window/alerts/PendingAlertsList.js
=> Fix validate/silence alert

datascience/src/pipeline/helpers/spatial.py, datascience/tests/test_pipeline/test_flows/test_notify_beacon_malfunctions.py, datascience/tests/test_pipeline/test_helpers/test_spatial.py
=> Fix compute_movement_metrics time_emitting_at_sea computation

frontend/src/features/measurements/CustomCircleRange.js, frontend/src/features/measurements/Measurement.js, frontend/src/layers/MeasurementLayer.js, frontend/src/layers/styles/measurement.style.js
=> fix: Do not show center of line string measurement

datascience/src/pipeline/flows/last_positions.py, datascience/src/pipeline/queries/monitorfish/recent_positions_histogram.sql, datascience/src/pipeline/queries/monitorfish/seconds_since_most_recent_last_position.sql, datascience/src/pipeline/shared_tasks/healthcheck.py, datascience/tests/mocks.py, datascience/tests/test_pipeline/test_flows/test_last_positions.py, datascience/tests/test_pipeline/test_shared_tasks/test_healthcheck.py
=> Improve beacon malfunctions reliability

backend/src/main/resources/db/migration/internal/V0.156__Update_beacon_malfunctions_table.sql
=> Remove beacon malfunctions in end of malfunction column

frontend/src/domain/shared_slices/Vessel.ts
=> Fix bug of added reporting when vessel has no position

frontend/src/features/vessel_sidebar/VesselSidebar.tsx, frontend/src/features/vessel_sidebar/beacon_malfunctions/details/BeaconMalfunctionDetails.js, frontend/src/features/vessel_sidebar/fishing_activities/logbook_messages_resumes/LANMessageResume.js, frontend/src/features/vessel_sidebar/fishing_activities/logbook_messages_resumes/SpeciesAndWeightChart.js, frontend/src/features/vessel_sidebar/reporting/current/ReportingForm.js, frontend/src/features/vessel_visibility/TrackDepthRadio.js, frontend/src/ui/shared/rsuite-override.css
=> Fix various UI feedback before MEP

frontend/src/features/backoffice/edit_regulation/AuthorizedRadioButtonGroup.js, frontend/src/features/commonStyles/Input.style.js, frontend/src/features/layers/regulatory/RegulatoryTopic.js, frontend/src/features/layers/regulatory/RegulatoryZone.js, frontend/src/features/side_window/alerts_reportings/ReportingList.tsx, frontend/src/features/vessel_sidebar/fishing_activities/logbook_messages_resumes/PNOMessageResume.js, frontend/src/features/vessel_sidebar/reporting/Reporting.js, frontend/src/features/vessel_sidebar/reporting/current/ReportingForm.js, frontend/src/ui/shared/rsuite-override.css
- Resolve #1379
- Resolve #1381
- Resolve #1382 
----
=> Fix various UI components

frontend/cypress/e2e/layers_sidebar.spec.ts, frontend/src/domain/shared_slices/Layer.ts, frontend/src/features/layers/administrative/AdministrativeLayers.js, frontend/src/features/layers/base/BaseLayers.js, frontend/src/features/layers/regulatory/RegulatoryLayers.js, frontend/src/features/layers/regulatory/search/RegulatoryLayerSearch.js, frontend/src/features/layers/regulatory/search/RegulatoryLayerSearchResultList.js
=> Add Show results button in regulation search

.github/workflows/cicd.yml
=> Set Firefox version to 104.0.2 in CI e2e tests

frontend/cypress/e2e/layers_sidebar.spec.ts, frontend/src/features/layers/regulatory/search/RegulatoryLayerSearchInput.js, frontend/src/features/layers/regulatory/search/RegulatoryLayerSearchResultList.js
=> Fix showing of results in REG search

frontend/cypress/e2e/vessel_track.spec.ts, frontend/package-lock.json, frontend/package.json
=> Fix frontend vessel track on CTRL click

frontend/src/features/side_window/beacon_malfunctions/BeaconMalfunctionCard.js
=> Fix frontend malfunctions list on click focus

frontend/src/api/geoserver.js, frontend/src/features/layers/regulatory/RegulatoryLayers.js
=> Fix regulation layers not saved when refreshing the window

datascience/src/pipeline/queries/fmc/beacons.sql
=> Fix vessel_id select naming

datascience/src/pipeline/queries/monitorfish/beacon_malfunctions_for_last_positions.sql
=> Remove malfunctions of non ACTIVATED beacons from last_positions

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/LogbookReportRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetVesselPositions.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBLogbookReportRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/GetVesselPositionsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepositoryITests.kt
=> Show last positions from last acknowledged message

datascience/src/pipeline/flows/scrape_legipeche.py
=> Run Scrape Legipeche flow with default (local) executor

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetLogbookMessages.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/GetLogbookMessagesUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/TestUtils.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/VesselControllerITests.kt, frontend/src/layers/styles/administrativeAndRegulatoryLayers.style.ts, frontend/src/layers/styles/utils.test.ts, frontend/src/layers/styles/utils.ts, frontend/src/layers/utils.test.ts, frontend/src/layers/utils.ts, frontend/src/ui/theme.ts
- Resolve #957
- Resolve #1420
----
=> Fix layers color and species group codes for COE/COX/CRO messages

frontend/.eslintrc.js, frontend/config/jest.config.js, frontend/src/domain/use_cases/beaconMalfunction/openBeaconMalfunctionInKanban.ts, frontend/src/domain/use_cases/reporting/deleteReporting.ts, frontend/src/domain/use_cases/vessel/showVesselsLastPosition.ts, frontend/src/features/side_window/alerts_reportings/ReportingList/index.tsx, frontend/src/features/vessel_sidebar/reporting/current/ReportingForm.tsx, frontend/src/hooks/useTable/index.tsx, frontend/src/hooks/useTable/types.ts, frontend/src/layers/styles/isForbiddenPeriod.test.ts, frontend/src/types.ts, frontend/src/ui/IconButton.tsx, frontend/src/ui/icons/constants.ts, frontend/src/ui/icons/index.tsx, frontend/src/utils/__tests__/downloadAsCsv.test.ts, frontend/src/utils/downloadAsCsv.ts
=> Add side window reporting list CSV download

frontend/cypress/e2e/side_window_beacon_malfunctions.spec.ts, frontend/src/features/side_window/beacon_malfunctions/BeaconMalfunctionCard.tsx, frontend/src/features/side_window/beacon_malfunctions/BeaconMalfunctionDetails.tsx, frontend/src/features/side_window/beacon_malfunctions/BeaconMalfunctionsBoard.tsx, frontend/src/features/side_window/beacon_malfunctions/StageColumn.tsx, frontend/src/features/side_window/beacon_malfunctions/VesselStatusSelect.tsx, frontend/src/features/side_window/beacon_malfunctions/beaconMalfunctions.tsx
=> Add status filter in beacon malfunctions

datascience/src/pipeline/queries/cross/expand_facade_geometries.sql
=> Add query to expand facades areas without overlap

frontend/src/domain/types/regulation.ts, frontend/src/layers/styles/administrativeAndRegulatoryLayers.style.ts, frontend/src/layers/styles/isForbiddenPeriod.test.ts, frontend/src/layers/styles/isForbiddenPeriod.ts
Should be red:
Should not be red:
----
=> Fix REG zone not in red when always forbidden

frontend/src/domain/types/regulation.ts, frontend/src/layers/styles/isForbiddenPeriod.test.ts, frontend/src/layers/styles/isForbiddenPeriod.ts, frontend/src/layers/styles/utils.test.ts, frontend/src/layers/styles/utils.ts
=> Fix handling of annual recurrence

frontend/cypress/e2e/layers_sidebar.spec.ts, frontend/cypress/mappings/regulatory-search-bbox.json, frontend/src/api/geoserver.js, frontend/src/domain/entities/beaconMalfunction/index.ts, frontend/src/layers/styles/isForbiddenPeriod.test.ts
- Resolve #1560
- Resolve #1559 
----
=> Fix reg search by zone

datascience/src/pipeline/data/manually_added_ports.csv
=> Add some ports

datascience/src/pipeline/flows_config.py, infra/remote/data-pipeline/prefectdockeragent.sh
=> Add 'monitorfish' label on agent and flows

.github/dependabot.yml
=> Setup Dependabot for backend, datascience & frontend

frontend/package-lock.json, frontend/package.json
=> Fix broken date range picker width when parent is narrower

frontend/cypress/e2e/side_window_mission_form.spec.ts, frontend/cypress/support/commands/clickOutside.ts, frontend/cypress/support/commands/fill/index.ts, frontend/cypress/support/utils/waitFor.ts, frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/SeaControl/ComplianceField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/SeaControl/DevicesField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/SeaControl/FleetSegmentsField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/SeaControl/FormikVesselSearch.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/SeaControl/SpeciesField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/SeaControl/index.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/index.tsx, frontend/src/features/SideWindow/MissionForm/MainForm/MultiUnitPicker.tsx, frontend/src/features/SideWindow/MissionForm/MainForm/index.tsx, frontend/src/features/SideWindow/MissionForm/index.tsx, frontend/src/features/SideWindow/MissionList/FilterBar.tsx, frontend/src/features/SideWindow/SideWindowLauncher.tsx, frontend/src/features/SideWindow/alerts_reportings/ReportingList/constants.ts, frontend/src/features/SideWindow/alerts_reportings/ReportingList/index.tsx, frontend/src/features/SideWindow/index.tsx, frontend/src/features/VesselSearch/index.tsx, frontend/src/hooks/useTable/index.tsx, frontend/src/ui/NewWindow/LegacyNewWindow.js, frontend/src/ui/NewWindow/NewWindowContext.ts, frontend/src/ui/NewWindow/index.tsx, frontend/src/ui/NewWindow/types.ts, frontend/src/ui/NewWindow/useNewWindow.ts
A merged PR on `monitor-ui` closed #1657 automatically, so I reopen it here.
- Follow #1657
- Resolve #1381
----
=> Fix frontend ISO styles issues

frontend/src/domain/entities/layers/constants.ts, frontend/src/domain/entities/vessel/vessel.ts, frontend/src/features/map/layers/BaseLayer.tsx
- Utilisation de fonds de cartes gratuits et ouverts à la place de Mapbox
- Ajout d'un cache car le serveur ouvert ne cache pas les requêtes 
----
=> Add open light and dark base maps with cache

frontend/cypress/docker-compose.yml, frontend/src/api/__tests__/getEnvironmentVariable.test.ts, frontend/src/api/utils.ts
=> Fix getEnvironmentVariable function

frontend/src/ui/FrontendErrorBoundary.tsx
=> Remove error boundary error mesage

frontend/cypress/e2e/vessel_sidebar_controls.spec.ts, frontend/src/features/VesselSidebar/Controls/Control.tsx
=> Fix control type display name

datascience/src/pipeline/flows/missions.py, datascience/tests/test_pipeline/test_flows/test_missions.py
=> Filter missions_controls units on mission_ids before loading

frontend/cypress/e2e/side_window/mission_form/land_control.spec.ts, frontend/src/api/index.ts, frontend/src/api/port.ts, frontend/src/domain/types/missionAction.ts, frontend/src/domain/types/port.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/LandControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikPortSelect.tsx
=> Link ports to mission form land control

frontend/src/features/SideWindow/MissionForm/ActionList/Item.tsx
=> Update and fix mission action list UX & UI

frontend/cypress/e2e/side_window/mission_form/air_surveillance.spec.ts, frontend/cypress/e2e/side_window/mission_form/land_control.spec.ts, frontend/cypress/e2e/side_window/mission_form/sea_control.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/SideWindow/MissionForm/ActionForm/LandControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/SeaControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FleetSegmentsField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/Infraction.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/index.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/GearsField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/SpeciesField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/VesselField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/VesselFleetSegmentsField.tsx, frontend/src/features/SideWindow/MissionForm/ActionList/Item.tsx, frontend/src/features/SideWindow/MissionForm/MainForm/FormikMultiControlUnitPicker/ControlUnitSelect.tsx, frontend/src/features/SideWindow/MissionForm/MainForm/FormikMultiControlUnitPicker/index.tsx, frontend/src/features/SideWindow/MissionForm/MainForm/FormikMultiControlUnitPicker/types.ts, frontend/src/features/SideWindow/MissionForm/MainForm/FormikMultiControlUnitPicker/utils.ts, frontend/src/features/SideWindow/MissionForm/MainForm/index.tsx, frontend/src/features/SideWindow/MissionForm/constants.tsx, frontend/src/features/SideWindow/MissionForm/shared/FieldsetGroup.tsx, frontend/src/features/SideWindow/MissionForm/shared/FieldsetGroupSeparator.tsx, frontend/src/features/VesselSearch/index.tsx, frontend/src/ui/NoRsuiteOverrideWrapper.tsx
=> Update and fix mission form action forms UX & UI

frontend/src/features/SideWindow/MissionForm/ActionForm/AirControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionList/index.tsx
=> Add datepicker time to mission form air control

frontend/package-lock.json, frontend/package.json, frontend/src/domain/entities/layers/index.ts, frontend/src/domain/entities/map/constants.ts, frontend/src/domain/entities/mission/index.ts, frontend/src/domain/shared_slices/Map.ts, frontend/src/domain/use_cases/draw/addFeatureToDrawedFeature.ts, frontend/src/domain/use_cases/map/getCoordinatesExtent.ts, frontend/src/domain/use_cases/missions/addControlCoordinates.ts, frontend/src/domain/use_cases/missions/closeDraw.ts, frontend/src/domain/use_cases/missions/index.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/SeaControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiCoordinatesPicker.tsx, frontend/src/features/SideWindow/MissionForm/MainForm/FormikMultiZonePicker.tsx, frontend/src/features/map/draw/DrawModal.tsx, frontend/src/features/map/layers/DrawLayer.tsx, frontend/src/features/map/layers/styles/draw.style.ts
Attention, il reste quelques tâches dans ce ticket, mais la PR peut déjà être merge pour les tests utilisateurs
- #1875 
----
=> Add control points in missions form

frontend/src/features/SideWindow/MissionForm/index.tsx
=> Fix mission form edition api call

backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaMissionActionRepositoryITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/TestUtils.kt
=> Add missing test for mission action repository update

frontend/src/features/map/Map.js
=> Do not show missions layers in production

frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/cypress/e2e/side_window/mission_list/filter_bar.spec.ts, frontend/cypress/e2e/side_window/mission_list/sea_front_filter.spec.ts, frontend/src/constants/index.ts, frontend/src/domain/controlUnits/utils.ts, frontend/src/domain/entities/alerts/constants.ts, frontend/src/domain/entities/mission/filters/seaFrontFilterFunction.ts, frontend/src/domain/entities/mission/hooks/useGetFilteredMissionsQuery.ts, frontend/src/domain/entities/mission/types.ts, frontend/src/domain/shared_slices/Mission.ts, frontend/src/features/SideWindow/MissionForm/MainForm/index.tsx, frontend/src/features/SideWindow/MissionForm/types.ts, frontend/src/features/SideWindow/MissionList/FilterBar.tsx, frontend/src/features/SideWindow/MissionList/index.tsx, frontend/src/features/SideWindow/MissionList/types.ts, frontend/src/features/SideWindow/SubMenu/Item.tsx, frontend/src/features/SideWindow/SubMenu/index.tsx
- #1777 (Bouton "Centrer sur la carte")
- Resolve #1959
- Resolve #1960
- Resolve #1860 (Champ "Ordre de missions")
- Resolve #1957
- Resolve #1962 
----
=> [Missions] Modification des filtres façades, unités et diverses corrections

frontend/src/features/SideWindow/MissionList/constants.ts, frontend/src/hooks/useTable/index.tsx, frontend/src/ui/card-table/CardTableColumnTitle.tsx
=> [Mission] Fix sorting in mission list

frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/src/api/index.ts, frontend/src/domain/shared_slices/SideWindow.ts, frontend/src/features/SideWindow/MissionForm/index.tsx, frontend/src/features/SideWindow/MissionForm/shared/DeletionConfirmationDialog.tsx, frontend/src/features/SideWindow/MissionForm/shared/DraftCancellationConfirmationDialog.tsx, frontend/src/libs/FrontendError.ts, infra/configurations/application-local.properties
[Description]
- Resolve #1911
----
=> [Missions] Suppression de la mission

frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/src/api/mission.ts, frontend/src/features/SideWindow/MissionForm/index.tsx, frontend/src/features/SideWindow/MissionList/constants.ts, frontend/src/features/SideWindow/MissionList/index.tsx
=> [Missions] Résoud plusieurs petits bugs bloquants pour le MEP

frontend/package-lock.json, frontend/package.json, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/ControlQualityField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FleetSegmentsField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/index.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikPortSelect.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/GearsField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/SpeciesField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/VesselFleetSegmentsField.tsx, frontend/src/features/SideWindow/MissionForm/ActionList/Item.tsx, frontend/src/features/SideWindow/MissionForm/MainForm/FormikMultiControlUnitPicker/ControlUnitSelect.tsx, frontend/src/features/SideWindow/MissionForm/shared/FormBody.tsx, frontend/src/features/SideWindow/MissionList/FilterBar.tsx, frontend/src/features/SideWindow/MissionList/utils.tsx, frontend/src/ui/formiks/FormikFilterTagBar.tsx
- Resolve #1886
- Resolve #2020
----
=> [Missions] Fixe plusieurs problèmes UI

frontend/src/store/reducers.ts
=> [Missions] Sauvegarder les filtres de la liste en local

frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/index.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikPortSelect.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/SpeciesField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/VesselFleetSegmentsField.tsx, frontend/src/features/SideWindow/MissionForm/shared/FieldGroup.tsx
=> [Missions] La case "Autres mesures et dispositifs" (section "engins") fait planter le formulaire

frontend/cypress/e2e/missions/controls_overlay.spec.ts, frontend/cypress/e2e/missions/missions_labels.spec.ts, frontend/cypress/e2e/missions/missions_map_button.spec.ts, frontend/cypress/e2e/missions/missions_overlay.spec.ts, frontend/cypress/e2e/side_window/mission_list/filter_bar.spec.ts, frontend/src/domain/shared_slices/DisplayedComponent.ts, frontend/src/domain/shared_slices/Mission.ts
- Resolve #2064 
- Resolve #2062 
----
=> Affichage des missions et filtrage à une semaine

frontend/cypress/e2e/side_window/mission_list/filter_bar.spec.ts, frontend/src/domain/entities/mission/hooks/useGetFilteredMissionsQuery.ts
=> [Missions] Résolution du bug de filtres des status

frontend/src/domain/entities/mission/index.ts, frontend/src/features/map/layers/Mission/SelectedMissionActionsLayer/index.tsx, frontend/src/features/map/layers/Mission/SelectedMissionLayer.tsx, frontend/src/features/map/layers/Mission/constants.ts
=> [Missions] Affichage de la mission et des actions lors de la création d'une mission

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/beacon_malfunctions/VesselBeaconMalfunctionsResume.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/ComputeFleetSegments.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/ComputeFleetSegmentsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/TestUtils.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/VesselControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPositionRepositoryITests.kt, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/VesselFleetSegmentsField.tsx
=> Ajout des espèces accessoires dans le calcul des segments de flottes

frontend/package-lock.json, frontend/package.json, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FleetSegmentsField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikPortSelect.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/GearsField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/SpeciesField.tsx, frontend/src/features/SideWindow/MissionForm/MainForm/FormikMultiControlUnitPicker/ControlUnitSelect.tsx
=> [Missions] Rechercher espèce par code FAO

frontend/cypress/e2e/side_window/mission_list/filter_bar.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/SideWindow/MissionList/FilterBar.tsx, frontend/src/features/SideWindow/MissionList/utils.tsx, frontend/src/utils/logSoftError.ts
=> [Missions] Filtrer les unités quand on sélectionne une administration

frontend/src/features/SideWindow/MissionList/constants.ts
=> [Missions] Il ne faut pas que les notes libres comptent comme un contrôle dans la vue liste

frontend/src/constants/index.ts
[Description]
- Resolve #2057
----
=> [Missions] Mettre l'onglet SA en dessous de NAMO

frontend/src/features/SideWindow/MissionList/constants.ts, frontend/src/features/SideWindow/MissionList/index.tsx
=> [Missions] Le tableau des missions ne s'affiche plus sur toute la largeur de la fenêtre

frontend/cypress/e2e/side_window/mission_list/filter_bar.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/SideWindow/MissionForm/MainForm/index.tsx, frontend/src/features/SideWindow/MissionList/FilterBar.tsx
=> [Missions] Agrandir en largeur la liste des administrations et de unités dans les filtres de la liste des missions

frontend/cypress/e2e/side_window/mission_form/air_control.spec.ts, frontend/cypress/e2e/side_window/mission_form/land_control.spec.ts, frontend/cypress/e2e/side_window/mission_form/sea_control.spec.ts, frontend/cypress/e2e/utils/getUtcDateInMultipleFormats.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/AirControlForm.tsx
=> [Missions] Ajouter le champ "Saisi par" dans le formulaire de contrôle aérien

.github/workflows/cicd.yml, backend/src/main/resources/db/testdata/V666.2__Insert_dummy_vessels.sql, datascience/config.py, datascience/src/pipeline/flows/vessels.py, datascience/tests/test_pipeline/test_flows/test_vessels.py, frontend/cypress/e2e/side_window/mission_form/sea_control.spec.ts, frontend/src/domain/entities/vessel/vessel.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/VesselField.tsx, frontend/src/features/SideWindow/MissionForm/ActionList/Item.tsx, frontend/src/features/SideWindow/MissionForm/types.ts, frontend/src/features/SideWindow/MissionList/constants.ts
=> Ajout d'un navire inconnu dans le CR de contrôle

frontend/src/features/SideWindow/MissionForm/ActionForm/index.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/index.tsx, frontend/src/features/SideWindow/MissionForm/MainForm/index.tsx, frontend/src/features/SideWindow/MissionForm/index.tsx
=> [Missions] Ajouter une nouvelle infraction génère "Une erreur est survenue"

frontend/src/features/SideWindow/MissionForm/ActionForm/AirControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/AirSurveillanceForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/LandControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/ObservationForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/SeaControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/ControlQualityField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/InfractionForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/index.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/GearsField.tsx, frontend/src/features/SideWindow/MissionForm/MainForm/index.tsx, frontend/src/features/SideWindow/MissionForm/shared/FormBody.tsx
=> [Missions] Revue UI de la colonne 3

frontend/src/features/SideWindow/MissionForm/ActionForm/AirControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/LandControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/SeaControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/Infraction.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/index.tsx
=> [Missions] Coquille dans le libellé des infractions autres

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/WebSecurityConfig.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/WebSecurityConfigITests.kt, datascience/docs/source/authentication.rst, datascience/docs/source/index.rst
=> [Authentification] Enlève la protection sur la route de redirection de la SPA

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/fao_area/FAOArea.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fao_areas/ComputeFAOAreasFromCoordinates.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fao_areas/ComputeVesselFAOAreas.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/ComputeFleetSegments.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/Utils.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/DataReferentialController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/FaoAreaController.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/faoAreas/ComputeFAOAreasFromCoordinatesUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/faoAreas/ComputeVesselFAOAreasUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/ComputeFleetSegmentsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/UtilsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/DataReferentialControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/FaoAreaControllerITests.kt, frontend/cypress/e2e/side_window/mission_form/sea_control_edition.spec.ts, frontend/src/api/faoAreas.ts, frontend/src/domain/use_cases/vessel/getFleetSegments.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/VesselFleetSegmentsField.tsx
=> [Missions] Calcul de `FAOArea` à partir de sa position de contrôle

frontend/package-lock.json, frontend/package.json
=> [Missions] Validation des dates de mission et d'action

frontend/src/features/SideWindow/MissionForm/ActionForm/shared/VesselField.tsx, frontend/src/features/VesselSearch/index.tsx
=> [Missions] Sélection d'un navire inconnu

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/SecurityConfig.kt
=> Ajout de `index.html` à la configuration de sécurité

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission_actions/MissionAction.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission_actions/MissionActionUTests.kt, frontend/cypress/e2e/side_window/mission_form/action_list.spec.ts, frontend/cypress/e2e/side_window/mission_form/air_control.spec.ts, frontend/cypress/e2e/side_window/mission_form/air_surveillance.spec.ts, frontend/cypress/e2e/side_window/mission_form/land_control.spec.ts, frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/cypress/e2e/side_window/mission_form/observation.spec.ts, frontend/cypress/e2e/side_window/mission_form/sea_control.spec.ts, frontend/cypress/e2e/side_window/mission_form/sea_control_edition.spec.ts, frontend/src/domain/types/missionAction.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/schemas.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikPortSelect.tsx, frontend/src/features/SideWindow/MissionForm/constants.tsx, frontend/src/features/SideWindow/MissionForm/index.tsx
=> Suppression du `portName` dans les actions de mission

frontend/cypress/e2e/side_window/mission_form/action_list.spec.ts, frontend/cypress/e2e/side_window/mission_form/sea_control_edition.spec.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/GearsField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/SpeciesField.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/VesselFleetSegmentsField.tsx
=> [Missions] Modification de `faoArea` après le changement d'un navire du contrôle

backend/src/main/resources/db/migration/internal/V0.223__Update_facade_type.sql
=> [Facade] Ajout de la façade Mayotte

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission_actions/MissionAction.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission_actions/MissionActionUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/AddMissionActionUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicBeaconMalfunctionControllerITests.kt, frontend/src/features/SideWindow/MissionForm/ActionForm/schemas.ts
=> [Missions] Ajout de la validation du champ trigramme utilisateur

frontend/src/features/VesselSidebar/Controls/Control.tsx, frontend/src/features/VesselSidebar/Controls/GearOnboard.tsx, frontend/src/features/VesselSidebar/Controls/Infraction.tsx
=> Ajout des marges dans le résumé des contrôles

frontend/src/features/SideWindow/MissionForm/ActionForm/LandControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/SeaControlForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/schemas.ts, frontend/src/features/SideWindow/MissionForm/utils.tsx
=> [Missions] Gestion de la validation selon l'état de la mission

infra/configurations/frontend/.env.dev, infra/configurations/frontend/.env.local, infra/configurations/frontend/.env.prod
=> Fix OIDC URLs

backend/src/main/resources/db/migration/internal/V0.224__Delete_from_mission_actions.sql
=> Supprimer les `mission_actions` de la phase test

frontend/src/domain/entities/seaFront/constants.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikCoordinatesPicker.tsx
=> Move SA below NAMO in mission list submenu

frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikCoordinatesPicker.tsx
=> Remove useles OR in FormikCoordinatesPicker

frontend/cypress/e2e/side_window/mission_form/action_list.spec.ts, frontend/cypress/e2e/side_window/mission_form/air_control.spec.ts, frontend/cypress/e2e/side_window/mission_form/air_surveillance.spec.ts, frontend/cypress/e2e/side_window/mission_form/land_control.spec.ts, frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/cypress/e2e/side_window/mission_form/observation.spec.ts, frontend/cypress/e2e/side_window/mission_form/sea_control.spec.ts, frontend/cypress/e2e/side_window/mission_form/sea_control_edition.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/SideWindow/MissionForm/MainForm/index.tsx, frontend/src/features/SideWindow/MissionForm/index.tsx, frontend/src/features/SideWindow/MissionForm/shared/TitleStatusTag.tsx
=> [Missions] Modification de la clôture des missions

frontend/package-lock.json, frontend/package.json
=> [Missions] Modification du champ coordonnées DMD 

frontend/src/domain/use_cases/layer/regulation/__tests__/__mocks__/index.ts, frontend/src/domain/use_cases/layer/regulation/__tests__/searchRegulatoryLayers.test.ts, frontend/src/features/MapButtons/LayersSidebar/RegulatoryZones/search/constants.ts
=> [Réglementation] Fix de la recherche dans les ref. reg.

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/SentryConfig.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/ControllersExceptionHandler.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/SecurityConfigITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/BeaconMalfunctionControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/ControlObjectiveControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/DataReferentialControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/FaoAreaControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/FleetSegmentControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/ForeignFMCsControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/InfractionControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/MissionActionsControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/MissionsControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/OperationalAlertControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PortControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/ReportingControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/UserAuthorizationControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/VesselControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/HealthcheckControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PositionsControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicBeaconMalfunctionControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/UserManagementControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/security/BffFilterConfigITests.kt, infra/remote/docker-compose.yml
=> [Tech] Amélioration des erreurs et du restart du backend

frontend/src/features/VesselSearch/__tests__/mocks/index.ts, frontend/src/features/VesselSearch/__tests__/removeDuplicatedFoundVessels.test.ts, frontend/src/features/VesselSearch/utils.ts
=> [Recherche Navire] Fix la duplication de recherche quand un navire n'a pas de CFR

backend/src/main/resources/db/migration/internal/V0.227__Update_vessels_table.sql
=> Amélioration des performances du flow `last_positions` (Ajout d'index sur la table `vessels`)

datascience/src/pipeline/flows_config.py
=> Mise à jour des plannings de traitements de données liés aux contrôles

frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikCoordinatesPicker.tsx
=> [Missions] Fix de l'écran blanc lors de l'affichage d'un contrôle sans coordonnées

frontend/src/features/SideWindow/MissionForm/ActionForm/index.tsx, frontend/src/features/SideWindow/MissionForm/ActionList/Item.tsx, frontend/src/features/SideWindow/MissionForm/ActionList/index.tsx, frontend/src/features/SideWindow/MissionForm/MainForm/index.tsx
Avant
Après
Passe de 537px à 601px : gagne 64px.
----
=> [Missions] Agrandissement du formulaire de contrôle

frontend/package-lock.json, frontend/package.json
- MTES-MCT/monitor-ui#518
----
=> Bump @mtes-mct/monitor-ui from 7.6.0 to 7.6.2

datascience/config.py, datascience/src/pipeline/entities/prefect.py, datascience/src/pipeline/flows/clean_flow_runs.py, datascience/src/pipeline/flows_config.py, datascience/src/pipeline/shared_tasks/control_flow.py, datascience/src/pipeline/shared_tasks/dates.py
=> Add clean_flow_runs flow

datascience/src/pipeline/flows/regulations_checkup.py
=> Handle additionnal requests excpetions in regulations_checkup

frontend/src/features/SideWindow/AlertListAndReportingList/ReportingList/constants.ts, frontend/src/features/SideWindow/AlertListAndReportingList/ReportingList/index.tsx, frontend/src/ui/card-table/CardTable.tsx
=> [Signalements] Les boutons d'actions de la liste des signalement ne sont pas visibles

backend/pom.xml, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/OIDCProperties.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/ProtectedPathsAPIProperties.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/SuperUserAPIProperties.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/security/ApiKeyCheckFilterUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/security/UserAuthorizationCheckFilterUTests.kt
=> [Tech] Correction de la vulnérabilité critique

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/OIDCProperties.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/SpaController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/security/UserAuthorizationCheckFilter.kt, backend/src/main/resources/application.properties, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/UserAuthorizationControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/security/UserAuthorizationCheckFilterUTests.kt
=> [Cerbère] Fix d'une URL de validation du token user

datascience/src/pipeline/shared_tasks/control_flow.py, datascience/tests/test_pipeline/test_shared_tasks/test_control_flow.py
=> Handle Nones in filter_results task

frontend/cypress/e2e/backoffice/regulatory_zone_list.spec.ts, frontend/src/features/Backoffice/list_regulation/SearchRegulations.tsx
=> [Backoffice] Correction de la recherche de REG

frontend/cypress/e2e/sidebars/regulatory_layers.spec.ts, frontend/cypress/e2e/vessel_sidebar/control_buttons.spec.ts, frontend/src/domain/use_cases/layer/regulation/__tests__/__mocks__/regulatoryZones.ts, frontend/src/domain/use_cases/layer/regulation/__tests__/searchRegulatoryLayers.test.ts, frontend/src/features/MapButtons/LayersSidebar/RegulatoryZones/search/constants.ts, frontend/src/features/VesselSidebar/actions/TrackRequest/index.tsx, frontend/src/features/VesselSidebar/actions/animate_to_track/index.tsx, frontend/src/features/VesselSidebar/actions/hide_non_selected_vessels/index.tsx, frontend/src/features/VesselSidebar/actions/show_fishing_activities/index.tsx
- Resolve #2446
- Resolve #2440
----
=> [Fiche navire & Recherche REG] Correction des boutons de la fiche navire et amélioration de la recherche REG

frontend/src/domain/entities/beaconMalfunction/__tests__/getMalfunctionStartDateText.test.ts, frontend/src/domain/entities/beaconMalfunction/index.ts, frontend/src/domain/entities/beaconMalfunction/types.ts, frontend/src/features/Backoffice/fleet_segments/FleetSegmentsTable.tsx, frontend/src/features/Backoffice/tableCells.jsx, frontend/src/features/SideWindow/BeaconMalfunctionBoard/__tests__/getActionText.test.ts, frontend/src/features/SideWindow/BeaconMalfunctionBoard/beaconMalfunctions.tsx, frontend/src/features/VesselSidebar/beacon_malfunctions/resume/BeaconMalfunctionCard.tsx
- Resolve #2401
- Resove #2402
- Resolve #2486
- Resolve #2487
----
=> [Avaries VMS] Correction de bugs mineurs

datascience/src/pipeline/queries/fmc/natinf.sql
=> Exclude blocked infractions from Poseidon natinf query

frontend/cypress/e2e/vessel_sidebar/control_buttons.spec.ts, frontend/src/features/VesselSidebar/actions/TrackRequest/index.tsx
=> [Cartographie] Ne pas griser le bouton d'actions des positions de la fiche navire

frontend/src/api/index.ts, frontend/src/features/SideWindow/MissionForm/ActionForm/ObservationForm.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/Infraction.tsx, frontend/src/features/SideWindow/MissionForm/ActionList/Item.tsx, frontend/src/features/SideWindow/MissionForm/ActionList/utils.tsx, infra/configurations/application-dev.properties, infra/configurations/application-local.properties, infra/configurations/application-prod.properties
- Resolve #2587
- Resolve #2594
- Resolve #2595
----
=> [Cartographie & Missions] Correction de la récupération des navires sur `/light`

datascience/src/pipeline/queries/monitorfish/control_charter.sql
=> Ignorer les contrôles supprimés lors de la détermination des navires sous charte

frontend/src/hooks/authorization/useGetUserAuthorization.ts
=> [Authentification] Correction de l'affichage admin sur `/light` 

datascience/tests/test_pipeline/test_flows/test_controls.py
=> [Pipeline] Ajout des colonnes manquantes

backend/src/main/resources/db/testdata/V0.221.0__Insert_port_codes.sql, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPortRepositoryITests.kt, frontend/cypress/e2e/side_window/mission_form/land_control.spec.ts, frontend/src/features/CustomZone/components/CustomZones/index.tsx, frontend/src/features/SideWindow/MissionForm/ActionForm/shared/FormikPortSelect.tsx
=> [Missions] Enlever les tirets dans la recherche de ports de contrôles

datascience/src/pipeline/queries/monitorfish/vessels_that_should_emit.sql
=> Suppression du filtre par pavillon dans le module avaries VMS

frontend/src/features/SideWindow/MissionForm/ActionList/Item.tsx, frontend/src/features/SideWindow/MissionForm/ActionList/utils.tsx
=> [Missions] Afficher le nom du navire en entier dans la liste des contrôles d'une mission

frontend/src/features/MainWindow.tsx, frontend/src/features/SideWindow/SideWindowLauncher.tsx
=> [Missions] Correction de l'affichage du dialog quand le formulaire est modifié

frontend/src/features/map/layers/styles/dottedLayer.style.ts, frontend/src/features/map/layers/styles/draw.style.ts
=> [Recherche REG] Changer le style de la zone de sélection pour filtrer la carte

infra/docker/Dockerfile.DataPipeline
=> Réparation de l'image de la data pipeline

frontend/src/features/CustomZone/utils/computeCustomZoneStyle.ts
=> [Cartographie] Réduction de l'opacité dans les zones importées

datascience/src/pipeline/queries/monitorfish/current_catches.sql
=> Ignorer les données déclaratives ultérieures à la date actuelle pour le calcul des espèces à bord

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/GetActivityReports.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission_actions/GetActivityReportsUTests.kt
=> [Missions] Correction des act-rep à la débarque

frontend/cypress/e2e/vessel_sidebar/controls.spec.ts, frontend/cypress/e2e/vessel_sidebar/fishing.spec.ts, frontend/src/features/Logbook/components/VesselLogbook/DISMessageResume.tsx, frontend/src/features/Logbook/components/VesselLogbook/FARMessageResume.tsx, frontend/src/features/Logbook/components/VesselLogbook/FishingActivitiesSummary.tsx, frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/Haul.tsx, frontend/src/features/SideWindow/Alert/AlertListAndReportingList/ReportingList/utils.ts, frontend/src/features/SideWindow/BeaconMalfunctionBoard/BeaconMalfunctionDetails.tsx, frontend/src/features/VesselSidebar/Controls/InfractionsSummary.tsx, frontend/src/features/VesselSidebar/Reportings/Current/ReportingForm.tsx, frontend/src/features/map/draw/DrawModal.tsx
=> [UI] Correction des styles

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/InfractionController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicMissionActionsController.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PublicMissionActionsControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicMissionActionsControllerITests.kt, infra/configurations/application-dev.properties, infra/configurations/application-local.properties, infra/configurations/application-prod.properties
=> [RapportNav] Rajouter l'API des actions de missions

.github/workflows/trivy.yml
=> [Tech] Ajout de Trivy

backend/src/main/resources/db/migration/internal/V0.239__Update_analytics_tables.sql, datascience/src/pipeline/flows/control_units.py, datascience/src/pipeline/flows/missions.py
=> Suppression des constraintes de clé étrangère sur les tables `analytics`

datascience/src/pipeline/queries/monitorfish/compute_last_positions.sql, datascience/src/pipeline/shared_tasks/positions.py, datascience/tests/test_pipeline/test_flows/test_last_positions.py, datascience/tests/test_pipeline/test_shared_tasks/test_positions.py
=> Prendre en compte la couche des terres émergées dans la détermination du statut initial des avaries (en mer / à quai)

backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/security/BffFilterConfigITests.kt, backend/src/test/resources/application.properties, infra/configurations/application-dev.properties, infra/configurations/application-local.properties, infra/configurations/application-prod.properties
=> [Tech] Protection des sous-chemins `/management` (UPDATE ENV VAR)

frontend/src/domain/entities/alerts/constants.ts, frontend/src/domain/entities/alerts/types.ts, frontend/src/domain/types/reporting.ts, frontend/src/features/SideWindow/Alert/slice.ts
=> [Alertes] Ajout de Mayotte dans la liste des alertes Océan Indien

frontend/cypress/e2e/vessel_sidebar/controls.spec.ts
=> [Tech] Fixe les tests E2E pour le passage à 2024

frontend/src/features/SideWindow/MissionForm/MainForm/FormikSyncMissionFields.tsx
=> [Missions] Fix de la MAJ des missions

backend/build.gradle.kts, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/PnoAndLanAlertEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/RuleEntity.kt
=> [Tech] MAJ de Flyway

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/SecurityConfig.kt
En lien avec : https://github.com/MTES-MCT/monitorenv/issues/1123
----
=> [Tech] Ajout de la méthode OPTIONS dans les méthodes autorisées

.github/workflows/cicd-data-processing.yml, .github/workflows/cicd.yml, .github/workflows/push_to_nexus.yml, .github/workflows/trivy.yml
This reverts commit 8eb682e80a0a1fd12381ab3be13204629f450b80.
None
----
=> [Tech] Revert "Replace get latest action with up-to-date action"

frontend/cypress/e2e/sidebars/regulatory_layers.spec.ts, frontend/src/features/Regulation/components/RegulationSearch/ResultTopic.tsx
=> Recherche REG - Correction du nombre de zones affiché

.github/dependabot.yml
=> [Tech] Préfixe, étiquette et inclut les actions Github dans Dependabot

frontend/.eslintrc.js
- MTES-MCT/monitorenv#1132
----
=> [Tech] Ajoute un warning ESLint pour les operateurs nullish coalescing manquants

.github/dependabot.yml
=> [Tech] Réactive /datascience dans la config Dependabot

frontend/cypress/support/e2e.ts, frontend/src/env.d.ts, infra/configurations/frontend/.env.prod
=> [Tech] Ajout de la messagerie

frontend/config/jest.config.js
=> [Tech] Fixe les paths dans la config Jest

frontend/src/domain/types/reporting.ts, frontend/src/features/AdministrativeZone/components/AdministrativeZones/AdministrativeZone.tsx, frontend/src/features/AdministrativeZone/components/AdministrativeZones/AdministrativeZonesGroup.tsx, frontend/src/features/Logbook/components/VesselLogbook/LogbookSummary/summaries/FARMessageResume.tsx, frontend/src/features/MapButtons/shared/RightMenuOnHoverArea.tsx, frontend/src/features/Reporting/components/VesselReportings/Current/ReportingForm.tsx, frontend/src/features/Reporting/components/VesselReportings/ReportingCard.tsx, frontend/src/features/Reporting/components/VesselReportings/utils.ts, frontend/src/features/map/overlays/VesselCardOverlay/VesselCard.tsx, frontend/src/features/map/overlays/VesselCardOverlay/constants.ts
- Resolve #2806
- Resolve #2345
- Resolve #2866
----
=> [Fiche navire] Correction de quelques typos

frontend/cypress/e2e/vessel_sidebar/logbook.spec.ts, frontend/src/features/Logbook/Logbook.types.ts, frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/messages/LANMessage.tsx, frontend/src/features/Logbook/constants.ts
- Resolve #2980
- Resolve #2976 
----
=> [Fiche navire] Correction de l'affichage des espèces des LANs

frontend/package-lock.json, frontend/package.json
- cf. https://github.com/MTES-MCT/monitor-ui/pull/1115
----
=> [Mission] Correction des boutons radios

frontend/src/App.tsx, frontend/src/auth/getOIDCConfig.ts
=> Tech - Ajout d'un param manquant pour le signout

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/authorization/GetAuthorizedUser.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/authorization/GetIsAuthorizedUser.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/UserAuthorizationController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/security/LoggedMessage.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/authorization/GetIsAuthorizedUserUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/UserAuthorizationControllerITests.kt
- Resolve https://github.com/MTES-MCT/monitorfish/issues/2836#issuecomment-2066898243
----
=> [Cerbère] Correction de l'API d'autorisation

frontend/cypress/e2e/side_window/alert_list/alerts_list.spec.ts, frontend/src/domain/entities/estimatedPosition.js, frontend/src/domain/entities/vessel/vessel.ts, frontend/src/domain/shared_slices/Layer.ts, frontend/src/domain/use_cases/map/clickOnMapFeature.ts, frontend/src/domain/use_cases/vessel/showVessel.ts, frontend/src/features/SideWindow/Alert/SilencedAlerts/fields/VesselField.tsx, frontend/src/features/VesselSearch/index.tsx, frontend/src/features/VesselSearch/utils.ts, frontend/src/features/VesselSidebar/actions/TrackRequest/TrackDepthSelection.tsx, frontend/src/features/map/layers/Vessel/VesselsLabelsLayer.tsx, frontend/src/features/map/layers/Vessel/VesselsLayer/index.tsx, frontend/src/features/map/overlays/VesselCardOverlay/index.tsx
- Resolve #1695
- Resolve #3050 
- #3115
----
=> [Fiche navire] Refacto de l'ajout de l'identifiant navire

backend/src/main/resources/db/migration/internal/V0.252__Update_analytics_controls_full_data_view.sql
- Resolve #2848
- Resolve #3056
=> Ajout des infos de PV et de commentaires dans la vue `analytics_controls_full_data`

.github/workflows/cicd.yml
=> [Tech] Requiert les tests unitaires avant de pousser vers le registre dans la CI

frontend/cypress/e2e/external_monitorfish.spec.ts, frontend/cypress/e2e/nav_monitorfish.spec.ts, frontend/cypress/e2e/vessel_sidebar/offline_management.spec.ts, frontend/src/domain/entities/authorization/constants.ts, frontend/src/features/VesselSidebar/Body.tsx, frontend/src/features/VesselSidebar/Summary/index.tsx, frontend/src/features/VesselSidebar/Tabs.tsx
=> Fiche navire - Afficher les informations de positions du navire actuel pour les utilisateurs externes

frontend/src/features/MainWindow/components/MapButtons/FavoriteVessels/FavoriteVessel.tsx
=> [Navires suivis] Corriger l'UI de la liste des navires favoris

backend/build.gradle.kts, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/FleetSegmentEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/ForeignFmcEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/LastPositionEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/LogbookReportEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/MissionActionEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/PendingAlertEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/ReportingEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/RiskFactorsEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/SilencedAlertEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/VesselEntity.kt
=> [Tech] Update spring-data-jpa dependencies

frontend/.env.example, frontend/.env.local.defaults, frontend/src/env.d.ts, frontend/src/index.tsx, infra/docker/docker-compose.cypress.yml, infra/docker/docker-compose.puppeteer.yml
=> [Tech] Ajout de la release sur Sentry

frontend/cypress/e2e/side_window/mission_form/action_list.spec.ts, frontend/src/features/Mission/components/MissionForm/ActionList/EnvActionCard.tsx, frontend/src/features/Mission/components/MissionForm/ActionList/FishActionCard.tsx, frontend/src/features/Mission/components/MissionForm/ActionList/styles.ts, frontend/src/features/Mission/components/MissionForm/index.tsx
- Resolve #3038
- Resolve #3023 
----
=> [Mission] Correction de l'affichage de la bannière et de la note libre

frontend/cypress/e2e/side_window/mission_form/sea_control_edition.spec.ts, frontend/puppeteer/e2e/missions.spec.ts, frontend/src/features/Mission/components/MissionForm/MainForm/FormikMultiControlUnitPicker/ControlUnitSelect.tsx, frontend/src/features/Mission/components/MissionForm/MainForm/FormikMultiControlUnitPicker/__tests__/mocks/dummy.ts, frontend/src/features/Mission/components/MissionForm/MainForm/FormikMultiControlUnitPicker/__tests__/utils.test.ts, frontend/src/features/Mission/components/MissionForm/MainForm/FormikMultiControlUnitPicker/index.tsx, frontend/src/features/Mission/components/MissionForm/MainForm/FormikMultiControlUnitPicker/utils.ts, frontend/src/features/Mission/components/MissionForm/index.tsx
- Resolve #3184 
- Affichage d'une unité dans le formulaire même quand l'unité n'est pas dans la liste des unités du référentiel
----
=> [Mission] Permettre l'enregistrement d'une mission valide mais non-complétée

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBLogbookReportRepository.kt, frontend/src/features/PriorNotification/components/PriorNotificationCard/index.tsx
=> [Préavis] Corrige le comptage des signalements sur la liste et la largeur de la fiche

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/actrep/JDPToFaoAreas.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/actrep/JointDeploymentPlan.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/actrep/species.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/MissionActionsRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fao_areas/ComputeVesselFAOAreas.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/mission_actions/GetActivityReports.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/mission_actions/dtos/ActivityReport.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/ActivityReportDataOutput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/cache/CaffeineConfiguration.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaFleetSegmentRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaMissionActionsRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/actrep/JointDeploymentPlanUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/faoAreas/ComputeFAOAreasFromCoordinatesUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/mission_actions/GetActivityReportsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/MissionActionsControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaFleetSegmentRepositoryITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaMissionActionRepositoryITests.kt, frontend/cypress/e2e/side_window/mission_list/export_activity_reports.spec.ts, frontend/src/features/ActivityReport/components/ExportActivityReportsDialog/csvMap.ts, frontend/src/features/ActivityReport/types.ts
- Resolve #3157
- Resolve #2929
----
=> [Act-Rep] Correction du double comptage des contrôles

frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/styles.ts
=>  [Fiche navire] Correction de l'affichage des espèces

frontend/package-lock.json, frontend/package.json, frontend/puppeteer/setup.ts
=> [Tech] Mise-à-jour de Puppeteer

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/prior_notification/PnoType.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/prior_notification/PnoTypeRule.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/risk_factor/VesselRiskFactor.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/PnoTypeRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/ComputeFleetSegments.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputePnoTypes.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputeRiskFactor.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/cache/CaffeineConfiguration.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/PnoTypeEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/PnoTypeRuleEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPnoTypeRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBPnoTypeRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputePnoTypesUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputeRiskFactorUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/TestUtils.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPnoTypeRepositoryITests.kt
=>  [Préavis] Calculer le type de PNO, les segments et la note de risque pour les préavis manuels

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/logbook/LogbookFishingCatch.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/input/ManualPriorNotificationFishingCatchInput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/LogbookMessageCatchDataOutput.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepositoryITests.kt, frontend/cypress/e2e/side_window/prior_notification_card/card.spec.ts, frontend/src/features/Logbook/Logbook.types.ts, frontend/src/features/Logbook/LogbookMessage.types.ts, frontend/src/features/Logbook/__tests__/utils.test.ts, frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/messages/LogbookMessage.tsx, frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/messages/PNOMessage.tsx, frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/messages/common/SpecyCatch.tsx, frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/messages/constants.tsx, frontend/src/features/Logbook/components/VesselLogbook/types.ts, frontend/src/features/Logbook/utils.ts, frontend/src/features/PriorNotification/components/PriorNotificationCard/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/ButtonsGroupRow.tsx, frontend/src/features/VesselSidebar/Equipment/resume/EquipmentResume.tsx, frontend/src/features/VesselSidebar/common/FlatKeyValue.tsx
=> Préavis - Affichage des PNO manuels

frontend/src/features/PriorNotification/components/PriorNotificationCard/__tests__/getHtmlContent.test.ts, frontend/src/features/PriorNotification/components/PriorNotificationCard/utils.tsx
=> Préavis - Ajout du nombre de poissons

datascience/src/pipeline/flows/vessels.py, datascience/tests/test_pipeline/test_flows/test_vessels.py
=> Bugfix sur le flow `vessels`

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/VerifyAndSendPriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationController.kt, backend/src/main/resources/db/migration/internal/V0.259__Index_logbook_reports_report_id_column.sql, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotificationUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/VerifyAndSendPriorNotificationUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationControllerITests.kt, frontend/cypress/e2e/side_window/prior_notification_card/card.spec.ts, frontend/cypress/e2e/side_window/prior_notification_card/error_handling.spec.ts, frontend/cypress/e2e/side_window/prior_notification_form/form.spec.ts, frontend/cypress/support/commands.ts, frontend/cypress/support/commands/countRequestsByAlias.ts, frontend/cypress/support/e2e.ts, frontend/src/features/PriorNotification/components/PriorNotificationForm/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/Row.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/cells/ActionButtonsCell.tsx, frontend/src/features/PriorNotification/priorNotificationApi.ts, frontend/src/features/PriorNotification/useCases/createOrUpdatePriorNotification.ts, frontend/src/features/PriorNotification/useCases/openPriorNotificationCard.ts, frontend/src/features/PriorNotification/useCases/openPriorNotificationForm.ts, frontend/src/features/PriorNotification/useCases/verifyAndSendPriorNotification.ts
=> [Préavis] – Optimise la vitesse de chargement d'ouverture d'une fiche

frontend/src/components/CustomGlobalStyle.ts, frontend/src/features/PriorNotification/components/PriorNotificationList/TableBodyLoader.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/columns.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/index.tsx, frontend/src/features/SideWindow/index.tsx, frontend/src/utils/isLegacyFirefox.ts
=> [Préavis] Créer un quick fix pour corriger les largeurs et le scroll du tableau dans la liste

frontend/cypress/e2e/vessel_sidebar/ers_vms.spec.ts, frontend/src/features/Vessel/Vessel.types.ts, frontend/src/features/VesselSidebar/Equipment/resume/EquipmentResume.tsx, frontend/src/features/VesselSidebar/Identity/index.tsx
- Resolve https://github.com/MTES-MCT/monitorfish/issues/3223#issuecomment-2188164163
----
=> Equipement VMS - Correction de l'erreur quand l'equipement n'est pas trouvé

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/logbook/messages/PNO.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/input/ManualPriorNotificationDataInput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/ManualPriorNotificationDataOutput.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotificationUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/fakers/LogbookMessageFaker.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationControllerITests.kt, frontend/cypress/e2e/side_window/prior_notification_form/form.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/Logbook/LogbookMessage.types.ts, frontend/src/features/PriorNotification/PriorNotification.types.ts, frontend/src/features/PriorNotification/components/PriorNotificationCard/utils.tsx, frontend/src/features/PriorNotification/components/PriorNotificationForm/Card.tsx, frontend/src/features/PriorNotification/components/PriorNotificationForm/Form.tsx, frontend/src/features/PriorNotification/components/PriorNotificationForm/constants.ts, frontend/src/features/PriorNotification/components/PriorNotificationForm/fields/FormikVesselSelect.tsx, frontend/src/features/PriorNotification/components/shared/DownloadButton/__tests__/getHtmlContent.test.ts, frontend/src/features/PriorNotification/components/shared/DownloadButton/index.tsx, frontend/src/features/PriorNotification/components/shared/DownloadButton/template.ts, frontend/src/features/PriorNotification/components/shared/DownloadButton/utils.tsx, frontend/src/features/PriorNotification/priorNotificationApi.ts
- Resolve #3288
- Resolve #3319
----
=> [Préavis] Ajouter dans le formulaire -12 m les autorisations de débarquement

frontend/cypress/e2e/side_window/prior_notification_form/form.spec.ts, frontend/src/features/PriorNotification/components/PriorNotificationForm/Card.tsx, frontend/src/features/PriorNotification/components/PriorNotificationForm/Form.tsx, frontend/src/features/PriorNotification/components/PriorNotificationForm/fields/FormikFishingCatchesMultiSelect/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationForm/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/FilterBar.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/FilterTags.tsx, frontend/src/features/PriorNotification/slice.ts, frontend/src/features/PriorNotification/useCases/openPriorNotificationForm.ts, frontend/src/features/PriorNotification/utils.ts, frontend/src/features/Vessel/components/VesselRiskFactor.tsx, frontend/src/hooks/useGetSpeciesAsOptions.ts, frontend/src/store/reducers.ts
=> [Préavis] Finalise et fixe plusieurs bugs liés au formulaire des préavis manuels

frontend/cypress/e2e/side_window/prior_notification_card/card.spec.ts, frontend/src/components/CountryFlag/index.tsx, frontend/src/components/CountryFlag/utils.ts, frontend/src/features/PriorNotification/components/PriorNotificationCard/index.tsx, frontend/src/features/PriorNotification/components/shared/DownloadButton/index.tsx, frontend/src/features/PriorNotification/components/shared/DownloadButton/utils.tsx, frontend/src/features/PriorNotification/priorNotificationApi.ts, frontend/src/features/PriorNotification/useCases/verifyAndSendPriorNotification.ts
=> Préavis - Envoyer un PNO

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/actrep/JointDeploymentPlan.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/actrep/JointDeploymentPlanUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/mission_actions/GetActivityReportsUTests.kt
- Correction des act-Rep pour les contrôles à la débarque sur plusieurs zones JDP
----
=> [Act-Rep] Correction des act-Rep pour les contrôles à la débarque sur plusieurs zones JDP

datascience/src/pipeline/flows_config.py
=> Tech - Suppression du flow PNO de l'init Prefect

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/LogbookReportRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/UpdatePriorNotificationNote.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/VerifyAndSendPriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/input/PriorNotificationDataInput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepositoryITests.kt, frontend/cypress/e2e/side_window/prior_notification_card/card.spec.ts, frontend/cypress/e2e/side_window/prior_notification_form/form.spec.ts, frontend/src/features/PriorNotification/PriorNotification.types.ts, frontend/src/features/PriorNotification/components/PriorNotificationCard/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationForm/index.tsx, frontend/src/features/PriorNotification/priorNotificationApi.ts, frontend/src/features/PriorNotification/useCases/createOrUpdateManualPriorNotification.ts, frontend/src/features/PriorNotification/useCases/updatePriorNotificationNote.ts
=> Préavis - Ajout de la note sur les préavis auto.

frontend/src/features/PriorNotification/components/PriorNotificationCard/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationForm/Card.tsx, frontend/src/features/PriorNotification/components/PriorNotificationForm/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/cells/ActionButtonsCell.tsx, frontend/src/features/PriorNotification/priorNotificationApi.ts, frontend/src/features/PriorNotification/slice.ts, frontend/src/features/PriorNotification/useCases/createOrUpdateManualPriorNotification.ts, frontend/src/features/PriorNotification/useCases/openPriorNotificationCard.ts, frontend/src/features/PriorNotification/useCases/openPriorNotificationForm.ts, frontend/src/features/PriorNotification/useCases/updatePriorNotificationNote.ts, frontend/src/features/PriorNotification/useCases/verifyAndSendPriorNotification.ts
=> Préavis - Aller chercher toutes les x secondes le nouvel état du préavis

frontend/cypress/e2e/side_window/prior_notification_card/card.spec.ts, frontend/cypress/e2e/side_window/prior_notification_card/utils.ts, frontend/cypress/e2e/side_window/prior_notification_form/form.spec.ts, frontend/src/components/ConfirmationModal.tsx, frontend/src/features/PriorNotification/components/PriorNotificationCard/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationForm/Card.tsx, frontend/src/features/PriorNotification/components/PriorNotificationForm/Form.tsx, frontend/src/features/PriorNotification/components/PriorNotificationForm/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/Row.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/cells/ActionButtonsCell.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/cells/StateCell.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/utils.ts, frontend/src/features/PriorNotification/components/PriorNotificationListButton.tsx, frontend/src/features/PriorNotification/components/shared/DownloadButton/index.tsx, frontend/src/features/PriorNotification/components/shared/TagBar.tsx, frontend/src/features/SideWindow/index.tsx
- Resolve #3242
- Resolve #3240
- Resolve #3319
- Resolve #2843
- Resolve #3241
- Resolve #3317
- Resolve #2869
----
=> Préavis - Correction UX/UI

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/SecurityConfig.kt, frontend/cypress/e2e/side_window/mission_form/sea_control_edition.spec.ts, frontend/src/features/Mission/components/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/index.tsx
- Reprise de https://github.com/MTES-MCT/monitorenv/pull/1557
- Resolve #3342
----
=>  Contrôles - On ne peut pas supprimer une infraction dans le formulaire

frontend/src/features/MainWindow/components/MapButtons/index.tsx, frontend/src/features/SideWindow/Menu/index.tsx
=> [Préavis] Active la liste des préavis pour les superusers

frontend/src/features/PriorNotification/components/PriorNotificationList/cells/TypesCell.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/columns.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/styles.ts
=> [Préavis] Ajoute le tag préavis 0 dans la liste

datascience/src/pipeline/flows/distribute_pnos.py, datascience/tests/test_pipeline/test_flows/test_distribute_pnos.py
=> Correction du statut 'Diffusé' / 'Hors diffusion' des PNOs logbook

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotifications.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationController.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationsITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationControllerITests.kt, frontend/cypress/e2e/side_window/prior_notification_form/form.spec.ts, frontend/src/features/Logbook/LogbookMessage.types.ts, frontend/src/features/PriorNotification/PriorNotification.types.ts, frontend/src/features/PriorNotification/components/PriorNotificationList/FilterBar.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/FilterTags.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/constants.ts, frontend/src/features/PriorNotification/components/PriorNotificationList/types.ts, frontend/src/features/PriorNotification/components/PriorNotificationList/utils.ts
=> [Préavis] Ajout d'un filtre "statut de diffusion" sur la liste

frontend/src/features/PriorNotification/components/PriorNotificationList/TableBodyEmptyData.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/TableBodyLoader.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/index.tsx, frontend/src/hooks/useLoadingState.ts, frontend/src/hooks/usePreviousIfTrue.ts
=> [Préavis] Lorsque le chargement de la liste est long, en délai ou en erreur, la dernière liste chargée est ré-affichée alors qu'elle ne devrait pas

datascience/src/pipeline/flows_config.py
=> Mise à jour des fréquences d'exécution des flows

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/prior_notification/PriorNotificationState.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputeManualPriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotification.kt, frontend/cypress/e2e/side_window/prior_notification_form/form.spec.ts, frontend/src/features/PriorNotification/PriorNotification.types.ts
=> Préavis – Correction des étiquettes des status

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/cache/CaffeineConfiguration.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaRecentPositionsMetricsRepository.kt
=> Ajout d'un cache sur le healthcheck (`sudden_drop_of_positions_received`)

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/logbook/LogbookMessageTypeMapping.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/logbook/LogbookOperationTypeMapping.kt
=> Tech - Log plus d'informations sur les erreurs

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/MonitorFishApplication.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/ControllersExceptionHandler.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/SentryController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/cache/CaffeineConfiguration.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBLogbookReportRepository.kt
=> Tech - Tests sur Sentry et ajout d'un cache

.github/workflows/cicd.yml
=> Update sourcemap upload in CI

frontend/src/features/Mission/components/MissionList/constants.ts, frontend/src/features/PriorNotification/components/PriorNotificationList/FilterBar.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/constants.ts, frontend/src/features/PriorNotification/components/PriorNotificationList/utils.ts
- Resolve #3481
- Resolve #3402
----
=>  Préavis - Evolutions filtre de dates

frontend/cypress/e2e/side_window/mission_form/action_list.spec.ts, frontend/src/features/Mission/components/MissionForm/ActionList/FishActionCard.tsx, frontend/src/features/Mission/components/MissionForm/ActionList/index.tsx, frontend/src/features/Mission/components/MissionForm/index.tsx
=>  Mission - Remettre la duplication d'une action 

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBLogbookReportRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBManualPriorNotificationRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepositoryITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaManualPriorNotificationRepositoryITests.kt
=>  Préavis – Ajout du CFR dans la recherche de navires

frontend/config/cypress.config.ts, frontend/vite.config.mts
=> Tech - Ajout du source map pour `sentry`

datascience/src/pipeline/flows/admin_areas.py, datascience/src/pipeline/flows/anchorages.py, datascience/src/pipeline/flows/control_units.py, datascience/src/pipeline/flows/facade_areas.py, datascience/src/pipeline/flows/fao_areas.py, datascience/src/pipeline/flows/foreign_fmcs.py, datascience/src/pipeline/flows/infractions.py, datascience/src/pipeline/flows/init_pno_types.py, datascience/src/pipeline/flows/missions.py, datascience/src/pipeline/flows/ports.py, datascience/src/pipeline/flows/vessels.py, datascience/src/pipeline/flows_config.py, datascience/src/pipeline/generic_tasks.py, datascience/src/pipeline/utils.py
=> Résolution des conflits de locks de BDD entre la sauvegarde quotidienne et les flows

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/cache/CaffeineConfiguration.kt
=> Tech - Augmentation de caches

frontend/cypress/e2e/side_window/logbook_prior_notification_form/form.spec.ts, frontend/src/features/Logbook/LogbookMessage.types.ts, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/Content.tsx, frontend/src/features/PriorNotification/components/PriorNotificationCard/index.tsx, frontend/src/features/PriorNotification/components/shared/DownloadButton/__tests__/getHtmlContent.test.ts, frontend/src/features/PriorNotification/components/shared/DownloadButton/index.tsx
-  Préavis - Correction du téléchargement des autorisations de débarquement
----
=> Préavis - Correction du téléchargement des autorisations de débarquement 

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/SecurityConfig.kt
=> Tech - whitelist jpg files in backend

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/LogbookReportEntity.kt, frontend/cypress/e2e/side_window/mission_form/sea_control.spec.ts, frontend/src/features/Mission/components/MissionForm/ActionForm/shared/VesselField.tsx, frontend/src/features/Vessel/apis.ts
=> [Missions] Afficher la taille du navire en dessous de ses informations dans le formulaire de contrôle

frontend/puppeteer/e2e/missions.spec.ts, frontend/puppeteer/e2e/utils.ts, frontend/puppeteer/setup.ts
=> [Tech] Corrige les utilitaires des tests E2E Puppeteer

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/prior_notification/PriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt
=> Préavis – Restaure la réinitialisation de l'état d'envoi durant la sauvegarde auto des préavis JPE

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaManualPriorNotificationRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepositoryITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaManualPriorNotificationRepositoryITests.kt
=> Préavis - Ne pas afficher dans les préavis à vérifier les préavis invalidés 

frontend/src/features/PriorNotification/components/PriorNotificationList/index.tsx
=> Préavis - Les lignes de détail des préavis doivent se refermer en cas de tri ou de filtrage du tableau

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaFleetSegmentRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaManualPriorNotificationRepository.kt
=> Préavis - Correction des PNOs à vérifier après une invalidation

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationPdfDocument.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicPriorNotificationController.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/public_api/PublicPriorNotificationControllerITests.kt, frontend/src/features/PriorNotification/components/shared/DownloadButton/index.tsx, frontend/src/features/PriorNotification/priorNotificationApi.ts, frontend/src/libs/FrontendError.ts
- Resolve #3537
- Resolve #3482
----
=> Préavis – Ajouter une route pour vérifier l'existence d'un PDF sans passer par des 404

backend/src/main/resources/db/migration/internal/V0.273__Update_logbook_reports_table.sql, datascience/src/pipeline/parsers/ers/log_parsers.py, datascience/src/pipeline/parsers/flux/flux.py, datascience/src/pipeline/parsers/utils.py, datascience/tests/test_pipeline/test_flows/test_logbook.py, datascience/tests/test_pipeline/test_parsers/test_ers.py, datascience/tests/test_pipeline/test_parsers/test_flux.py, datascience/tests/test_pipeline/test_parsers/test_utils.py
=> Ajout d'une colonne `activity_datetime_utc` dans la table logbook reports

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/vessel/Vessel.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetVessel.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/VesselDataOutput.kt, frontend/cypress/e2e/vessel_sidebar/ers_vms.spec.ts, frontend/src/features/Vessel/Vessel.types.ts, frontend/src/features/VesselSidebar/Equipment/resume/EquipmentResume.tsx
=> Fiche navire - Affichage de la version du logiciel JPE

datascience/src/pipeline/emails/templates/email_actions_to_units/email_actions_to_units.jinja, datascience/tests/test_data/emails/email_actions_to_units/expected_rendered_email.html, datascience/tests/test_data/emails/email_actions_to_units/expected_rendered_email_without_actions.html
Retrait d'une phrase de l'email aux unités
=> Retrait d'une phrase de l'email aux unités

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetVesselVoyage.kt
=> JPE - Correction de l'heure de la dernière marée

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fao_areas/GetFaoAreas.kt
=> Préavis - Supprime le second tri superflu des zones FAO

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/position/NetworkType.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/position/NetworkTypeUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/mappers/NAFMessageMapperUTests.kt
=> Positions VMS - Lorque le type de réseau est GSM, la position n'est pas traitée

datascience/src/pipeline/shared_tasks/control_units.py, datascience/tests/test_pipeline/conftest.py
=> Résolution du bug de diffusion des préavis quand un numéro de téléphone ou un email est un string vide

frontend/src/auth/hooks/useCustomAuth.tsx
=> Cerbère - Ajout d'un silent renew si le token est déjà expiré

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/SecurityConfig.kt
=> fix: add PATCH to allowed CORS methods

datascience/src/pipeline/flows/distribute_pnos.py, datascience/tests/test_data/emails/prior_notifications/expected_sms_1.txt
=> Ajout du libellé des segments dans les SMS de préavis

.github/workflows/cicd.yml, frontend/cypress/e2e/side_window/manual_prior_notification_form/behavior.spec.ts, frontend/cypress/e2e/side_window/manual_prior_notification_form/form.spec.ts, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/FormikExtraField.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/index.tsx
=> Préavis - calculer automatiquement le poids total de BFT

frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Form/FieldWithButton.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Form/FormikNameSelect.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Form/index.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Item.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/utils.ts, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/Form.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/Item.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/shared/TextareaForm.tsx, frontend/src/features/Reporting/components/VesselReportings/Summary/InfractionSuspicionSummary.tsx, frontend/src/features/Vessel/components/VesselSidebar/Equipment/resume/EquipmentResume.tsx, frontend/src/features/Vessel/components/VesselSidebar/common/FlatKeyValue.tsx
- Resolve #3208
- Resolve #3188
- Resolve #3083
- J'ai repris la PR Env https://github.com/MTES-MCT/monitorenv/pull/1653 
----
=> Unités - Corrections UI

frontend/cypress/e2e/side_window/manual_prior_notification_form/behavior.spec.ts, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/FormikExtraField.tsx
=> Préavis - La saisie des poids d'espadon sur les préavis 0 plante

frontend/cypress/e2e/side_window/manual_prior_notification_form/behavior.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/PriorNotification/components/LogbookPriorNotificationForm/Form.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/FormikExtraField.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/index.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/styles.ts
- Resolve #3508
- Resolve #3666
- Resolve #3211
----
=> Préavis - Cache les documents attachés sur Monitor Ext

frontend/src/api/constants.ts, frontend/src/features/PriorNotification/components/LogbookPriorNotificationForm/index.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/index.tsx, frontend/src/features/PriorNotification/hooks/useInterval.ts, frontend/src/features/PriorNotification/priorNotificationApi.ts, frontend/src/features/PriorNotification/useCases/openLogbookPriorNotificationForm.ts, frontend/src/features/PriorNotification/useCases/openPriorNotificationCard.ts, frontend/src/features/PriorNotification/useCases/refreshPriorNotification.ts, frontend/src/features/SideWindow/useCases/addSideWindowBanner.ts
=>  Préavis - Un préavis envoyé reste "En cours de diffusion" 

datascience/src/pipeline/queries/ocan/eu_vessels.sql
=> Ajout de navires britanniques manquants

frontend/package-lock.json, frontend/package.json, frontend/vite.config.ts
=> Tech - Ré-écrit le valeur `pointer-events` dans le bundle Frontend

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/reporting/GetVesselReportings.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/reporting/GetVesselReportingsUTests.kt, frontend/src/features/InterestPoint/components/InterestPointMapButton/constants.ts, frontend/src/features/Regulation/components/RegulationSearch/ResultTopic.tsx, frontend/src/features/Regulation/components/RegulationSearch/ResultZones.tsx
- Resolve #3653
- Resolve #3695 
- Resolve #3692 
----
=> Zones REG - Corriger l'affichage de la liste des zones et autres corrections

frontend/src/auth/hooks/useCustomAuth.tsx
- Ajout de l'utilisateur dans Sentry
----
=> Tech - Ajout de l'utilisateur dans Sentry

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/prior_notification/PriorNotification.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotifications.kt
- Resolve #3740
- Amélioration des performances de la requête des PNOs (voir commentaires)
----
=> Tech - Amélioration des performances de la requête des PNOs

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetLogbookMessages.kt, backend/src/main/resources/db/testdata/V666.5.0__Insert_logbook_raw_messages_and_reports.sql, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetLogbookMessagesITests.kt
=> Fiche navire – Exclure les préavis invalidés du JPE

frontend/src/domain/entities/alerts/constants.ts
=> Alerte - Renommage de l'alerte DEP

frontend/cypress/e2e/side_window/manual_prior_notification_form/behavior.spec.ts, frontend/src/features/PriorNotification/__tests__/getFormDataFishingCatchesFromFormValuesFishingCatches.test.ts, frontend/src/features/PriorNotification/__tests__/getFormValuesFishingCatchesFromFormDataFishingCatches.test.ts, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/FormikExtraField.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/FormikMainField.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/index.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/index.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/types.ts, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/utils.tsx, frontend/src/features/PriorNotification/constants.ts, frontend/src/features/PriorNotification/useCases/openManualPriorNotificationForm.ts, frontend/src/features/PriorNotification/utils.ts
=> Préavis – La saisie des poids d'espadon sur les préavis 0 plante

frontend/index.html
=> Statistiques - Utilise le Matomo Beta plutôt que celui du MTE

frontend/cypress/e2e/backoffice/new_regulation.spec.ts, frontend/src/features/Regulation/utils.ts
=> Backoffice REG - Ajout du Règlement (UE) 2024/2594

frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/FormikExtraField.tsx, frontend/src/features/PriorNotification/components/ManualPriorNotificationForm/fields/FormikFishingCatchesMultiSelect/FormikMainField.tsx
=> Préavis – Aligne visuellement le champ quantité SWO avec son poids dans le formulaire

frontend/src/features/PriorNotification/components/ReportingList.tsx, frontend/src/features/Reporting/components/CurrentReportingList/Content.tsx, frontend/src/features/Reporting/components/CurrentReportingList/index.tsx, frontend/src/features/Vessel/components/VesselSidebar/ReportingList/index.tsx
=> Signalements - Il n'y a plus de scroll dans la liste des signalement

frontend/cypress/e2e/side_window/logbook_prior_notification_form/behavior.spec.ts, frontend/src/features/PriorNotification/components/PriorNotificationList/index.tsx
=> Urgent - Corrige l'enregistrement de commentaire dans le formulaire de préavis auto

frontend/src/features/Logbook/__tests__/__mocks__/logbookMessageWithCorrections.ts, frontend/src/features/Logbook/__tests__/utils.test.ts, frontend/src/features/Logbook/utils.ts
=>  Fiche navire - Le poids total de captures par espèce n'est pas correct dans certains cas

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaManualPriorNotificationRepository.kt, frontend/src/features/PriorNotification/components/PriorNotificationList/constants.ts, frontend/src/features/PriorNotification/components/PriorNotificationList/utils.tsx
=> Préavis - Prendre en compte les préavis du passé dans le nombre de préavis à valider

frontend/src/features/Vessel/layers/style.ts
=> VMS - Certains navires ne s'affichent pas avec last_positions

datascience/src/pipeline/flows_config.py
=> Résolution du conflit d'`alert_config_name` sur les alertes de pêche en zone RTC

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/SecurityConfig.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/prior_notification/filters/PriorNotificationSubscribersFilter.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationSubscribers.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationSubscriberController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/proxy/ScriptProxyController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/cache/CaffeineConfiguration.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationSubscribersUTests.kt, frontend/cypress/e2e/back_office/prior_notification_subscriber_table/filter_bar.spec.ts, frontend/cypress/e2e/back_office/prior_notification_subscriber_table/utils.ts, frontend/index.html, frontend/src/App.tsx, frontend/src/constants/index.ts, frontend/src/features/PriorNotification/PriorNotificationSubscriber.types.ts, frontend/src/features/PriorNotification/backoffice.slice.ts, frontend/src/features/PriorNotification/components/PriorNotificationList/Row.tsx, frontend/src/features/PriorNotification/components/PriorNotificationList/utils.tsx, frontend/src/features/PriorNotification/components/PriorNotificationSubscriberTable/FilterBar.tsx, frontend/src/features/PriorNotification/components/PriorNotificationSubscriberTable/constants.tsx, frontend/src/features/PriorNotification/components/PriorNotificationSubscriberTable/index.tsx, frontend/src/features/PriorNotification/components/PriorNotificationSubscriberTable/types.ts, frontend/src/features/PriorNotification/components/PriorNotificationSubscriberTable/utils.tsx, frontend/src/features/PriorNotification/priorNotificationSubscriberApi.ts, frontend/src/hooks/useSmallChat.tsx, frontend/vite.config.ts
=> Paramétrage diffusion préavis – Corrections et ajout d'un filtre

frontend/package-lock.json, frontend/package.json
=> [Tech] Migre cypress-plugin-snapshots vers le repo hébergé MTES-MCT

frontend/package-lock.json, frontend/package.json, frontend/vite.config.ts
=> Sentry - Ajout de la config pour envoyer les sources maps

frontend/cypress/e2e/side_window/mission_form/sea_control_edition.spec.ts, frontend/src/features/Mission/components/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/index.tsx
=> CR de contrôle - L'édition d'une infraction édite la mauvaise infraction

datascience/src/pipeline/flows/notify_beacon_malfunctions.py, datascience/src/pipeline/sms/end_of_malfunction.jinja, datascience/src/pipeline/sms/malfunction_at_port_initial_notification.jinja, datascience/src/pipeline/sms/malfunction_at_port_reminder.jinja, datascience/src/pipeline/sms/malfunction_at_sea_initial_notification.jinja, datascience/src/pipeline/sms/malfunction_at_sea_reminder.jinja, datascience/src/pipeline/sms/malfunction_initial_notification_unsupervised_beacon.jinja, datascience/tests/test_data/sms/END_OF_MALFUNCTION.txt, datascience/tests/test_data/sms/MALFUNCTION_AT_PORT_INITIAL_NOTIFICATION.txt, datascience/tests/test_data/sms/MALFUNCTION_AT_PORT_REMINDER.txt, datascience/tests/test_data/sms/MALFUNCTION_AT_SEA_INITIAL_NOTIFICATION.txt, datascience/tests/test_data/sms/MALFUNCTION_AT_SEA_REMINDER.txt
=> Ajouter le nom du navire dans les SMS d'avarie VMS

datascience/src/pipeline/queries/monitorfish/compute_last_positions.sql
=> Récupération des données navires pour les navires sans CFR

backend/src/main/resources/application.properties, infra/docker/app/Dockerfile
=> Messagerie - Le chat n'est plus visible en PROD

frontend/cypress/e2e/main_window/vessel_sidebar/identity.spec.ts
=> Tech - Corrrection d'un test cypress avec une date

datascience/src/pipeline/parsers/flux/childless_parsers.py, datascience/src/pipeline/parsers/flux/log_parsers.py, datascience/tests/test_pipeline/test_parsers/test_flux.py
=> Extraire les poids nets (et non vifs) des LAN au format FLUX

frontend/cypress/e2e/main_window/vessel_sidebar/logbook.spec.ts, frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/constants.ts, frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/index.tsx, frontend/src/features/Vessel/components/VesselSidebar/Identity.tsx
- Resolve #3205
- Resolve #2620
----
=> Fiche navire - Corrections sur le permis de navigation

frontend/src/features/Vessel/components/VesselSidebar/Identity.tsx
=> Tech - Correction d'une erreur de logique

frontend/src/features/Vessel/components/VesselSidebar/common/FlatTwoColumnKeyValue.tsx
=> Fiche navire - Correction UI sur l'onglet identité

frontend/src/features/Reporting/components/ReportingTable/columns.tsx, frontend/src/features/Reporting/components/ReportingTable/index.tsx, frontend/src/hooks/useTableVirtualizer.ts
=> Tech - Correction du scroll virtuel dans la liste des signalements

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/ApiClient.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/security/UserAuthorizationCheckFilter.kt, frontend/cypress/e2e/main_window/vessel_sidebar/control_buttons.spec.ts, frontend/cypress/e2e/main_window/vessel_sidebar/offline_management.spec.ts, frontend/src/api/APIWorker.tsx, frontend/src/features/Logbook/api.ts
- Resolve #3941
- Resolve #3940
----
=> Tech - Correction d'erreurs `sentry`

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt
=> Tech - Correction du healthcheck pour l'intégration

frontend/src/auth/utils.ts, frontend/src/features/Regulation/components/RegulatoryZoneMetadata/regulatoryReferences/RegulatoryReferencesDisplayed.tsx, frontend/src/hooks/useTracking.ts
=> Tech - Ajout de nouveau tracking Matomo

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/oidc/UserInfo.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/OIDCRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/proxy/ScriptProxyController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/security/BffFilterConfig.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/security/UserAuthorizationCheckFilter.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/cache/CaffeineConfiguration.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/oidc/APIOIDCRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/UserAuthorizationControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/security/BffFilterConfigITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/security/UserAuthorizationCheckFilterUTests.kt
=> Tech - Ajout d'un cache sur les requêtes `user_info` OIDC

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaLogbookReportRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBLogbookReportRepository.kt
- Fix `findFirstAcknowledgedDateOfTripBeforeDateTime` query perf
----
=> Tech - Amélioration des performances d'une requête `logbook`

datascience/src/pipeline/flows/ports.py
=> Réduction du rayon de `buffer` dans l'attribution de zones FAO aux ports 

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBLogbookReportRepository.kt
=> Tech - Amélioration des performances des requêtes `logbook`

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBLogbookReportRepository.kt, frontend/src/auth/components/Login.tsx
- Corrige le bouton de connexion ne s'affichant pas
----
=> Tech - Correction de la page de login

frontend/src/features/ProducerOrganizationMembership/components/ProducerOrganizationMembershipTable/FilterBar.tsx, frontend/src/features/ProducerOrganizationMembership/components/ProducerOrganizationMembershipTable/index.tsx, frontend/src/features/Reporting/components/ReportingTable/cells/ActionButtonsCell.tsx, frontend/src/features/Reporting/components/ReportingTable/columns.tsx, frontend/src/features/Reporting/components/ReportingTable/index.tsx, frontend/src/features/Vessel/components/VesselSidebar/Identity.tsx, frontend/src/features/commonComponents/ErrorToastNotification.tsx, frontend/src/pages/BackofficePage.tsx
- Resolve #3787
- Resolve #2620
- Resolve #3705
----
=> Signalements – Ajouter les signalements de type "observation" dans la vue liste des signalements

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/actrep/JointDeploymentPlan.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/mission_actions/GetActivityReportsUTests.kt
=> Act-Rep - Ajouter le double-comptage des contrôles PEL13 avec BFT

frontend/src/api/APIWorker.tsx, frontend/src/domain/use_cases/gearCode/getAllGearCodes.ts, frontend/src/domain/use_cases/species/getAllSpecies.ts, frontend/src/features/FleetSegment/components/FleetSegmentsBackoffice/FleetSegmentsTable.tsx, frontend/src/features/Regulation/components/RegulationForm/GearRegulation/index.tsx, frontend/src/features/Regulation/components/RegulationForm/index.tsx, frontend/src/features/Regulation/components/RegulationTables/index.tsx, frontend/src/features/SideWindow/index.tsx, frontend/src/store/index.ts
=> Tech - Correction des lenteurs au démarrage de l'application

datascience/src/pipeline/flows/missing_far_alerts.py, datascience/tests/test_pipeline/test_flows/test_missing_far_alerts.py
=> Prendre en compte les exemptions JPE dans les alertes de FAR manquant

frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/src/features/ControlUnit/components/ControlUnitListDialog/Item.tsx, frontend/src/features/ControlUnit/useCases/centerOnStation.ts, frontend/src/features/Mission/components/MissionForm/MainForm/FormikMultiControlUnitPicker/ControlUnitSelect.tsx, frontend/src/features/Mission/components/MissionForm/MainForm/FormikMultiControlUnitPicker/index.tsx
=> Mission - Pouvoir zoomer sur les bases d'une unité depuis la fiche Mission

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBLogbookReportRepository.kt
=> JPE - Augmenter la plage de dates pour les RET

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/reporting/ArchiveOutdatedReportings.kt, frontend/src/features/Alert/constants.ts
=> Archiver automatiquement les signalements FAR manquant 48h

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/InfractionCategory.kt
- Après une revue des catégories de Poséidon
----
=> Tech - Ajout des catégories d'infractions manquantes

datascience/src/pipeline/helpers/segments.py, datascience/tests/test_data/csv/catches.csv, datascience/tests/test_data/csv/segments.csv
=> Corriger l'attribution de segments dans le cas d'espèces cibles avec 0kg

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBReportingRepository.kt
=> Signalements - Augmenter la fenêtre de temps requêtée pour l'archivage automatique de signalements

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/MissionSource.kt, frontend/cypress/e2e/side_window/mission_list/sea_front_filter.spec.ts, frontend/cypress/mappings/get-missions.json, frontend/src/features/Mission/components/MissionForm/shared/ExternalActionsDialog.tsx, frontend/src/features/Mission/components/MissionList/constants.ts, frontend/src/features/Mission/mission.types.ts
-  Ajout de RapportNav dans les sources de missions
----
=> Mission - Ajout de `RapportNav` dans les sources de missions

frontend/src/features/Mission/components/MissionList/constants.ts
=> Tech - Ajout d'un status de mission manquant

backend/src/main/resources/db/migration/internal/V0.290__Update_analytics_controls_full_data_view.sql
=> Ajout des maillages et suppression des observations dans la vue `analytics_controls_full_data`

frontend/cypress/mappings/get-control_units.v2.json, frontend/package-lock.json, frontend/package.json, frontend/src/features/Mission/components/MissionForm/ActionForm/shared/FormikOtherControlsCheckboxes.tsx, frontend/src/features/Mission/components/MissionForm/MainForm/FormikMultiControlUnitPicker/index.tsx, frontend/src/features/Mission/components/MissionForm/useCases/updateOtherControlsCheckboxes.ts
=> Mission - Ajout de la section "Autres contrôles effectués par l'unité" pour les ULAM

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/MissionAction.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/GetAllMissions.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/dtos/InfractionFilterDTO.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/MissionController.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/GetAllMissionsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/MissionsControllerITests.kt, frontend/cypress/e2e/side_window/mission_list/filter_bar.spec.ts, frontend/cypress/e2e/side_window/mission_list/sea_front_filter.spec.ts, frontend/src/features/Mission/components/MissionList/FilterBar.tsx, frontend/src/features/Mission/components/MissionList/constants.ts, frontend/src/features/Mission/components/MissionList/constants.tsx, frontend/src/features/Mission/components/MissionList/hooks/useGetFilteredMissionsQuery.ts, frontend/src/features/Mission/components/MissionList/index.tsx, frontend/src/features/Mission/components/MissionList/slice.ts, frontend/src/features/Mission/components/MissionList/types.ts, frontend/src/features/Mission/monitorfishMissionApi.ts, frontend/src/ui/formiks/FormikFilterTagBar.tsx
- Resolve #3758
- Resolve #3396
----
=> Mission - Ajouter un filtre "mission sous JDP" et les infractions à la liste des missions

frontend/package-lock.json, frontend/package.json, frontend/src/features/LoadOffline/components/LoadOffline.tsx, frontend/src/features/Mission/components/MissionForm/ActionForm/shared/FormikMultiInfractionPicker/InfractionForm.tsx, frontend/src/features/Mission/components/MissionForm/shared/FieldsetGroup.tsx, frontend/src/pages/LightBackoffice.tsx, frontend/src/workers/README.md, frontend/src/workers/constants.ts, frontend/src/workers/serviceWorker.ts, frontend/src/workers/settings.ts, frontend/src/workers/unregisterServiceWorker.ts, frontend/src/workers/utils.ts, frontend/vite.config.ts
- Resolve #3890
- Corrections des marges du formulaire de contrôle
- Correction du service-worker et suppression du cache sur la réglementation
- Cache du fond de carte à communiquer aux équipes
- Ajout de la suppression du cache existant (reload)
- Ajout de la suppression du service-worker existant (unregister)
----
=> Tech & UI - Diverses améliorations

frontend/package-lock.json, frontend/package.json
=> Contrôles – Quand on modifie un point de contrôle dans les missions, ne pas effacer l'ancienne coordonnée afin de pouvoir la corriger

frontend/package-lock.json, frontend/src/features/FleetSegment/components/FleetSegmentsBackoffice/CreateOrEditFleetSegmentModal.tsx, frontend/src/features/FleetSegment/constants.ts
=> Backoffice segments de flottes - Supprimer une espèce cible

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationSubscriber.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationSubscribers.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/UpdatePriorNotificationSubscriber.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/PriorNotificationSubscriberController.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationSubscriberUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/GetPriorNotificationSubscribersUTests.kt, frontend/cypress/e2e/back_office/prior_notification_subscriber_form/form.spec.ts, frontend/package-lock.json, frontend/package.json
- Resolve #4085
- La MAJ des segment depuis `/prior_notification_subscribers` prenait les segments de totues les anneés, et pas seulement ceux de l'année en cours.
----
=> Tech - MAJ de monitor-ui

frontend/src/features/FleetSegment/apis.ts
- Do not throw when parsing with zod schema
----
=> Tech - Ne pas lever d'exception lorsqu'on parse avec `zod`

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/Utils.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/ComputeFleetSegmentsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/fleet_segment/UtilsUTests.kt
=> Segment de flotte - Erreur de calcul sur le segment "FR_ELE"

frontend/vite.config.ts
=> Tech - Suppression du minify

frontend/src/features/SideWindow/SideWindowLauncher.tsx, frontend/vite.config.ts
=> Tech - Suppression du re-render de la side window

frontend/cypress/e2e/main_window/my_account.spec.ts, frontend/cypress/e2e/main_window/new_features.spec.ts, frontend/src/api/api.ts, frontend/src/auth/utils.ts, frontend/src/components/ConfirmationModal.tsx, frontend/src/features/Account/components/Account.tsx, frontend/src/features/ActivityReport/components/ExportActivityReportsDialog/index.tsx, frontend/src/features/FavoriteVessel/components/FavoriteVessels/index.tsx, frontend/src/features/MainWindow/components/MapButtons/VesselLabels/EditVesselLabels.tsx, frontend/src/features/MainWindow/components/MapButtons/VesselVisibility/EditVesselVisibility.tsx, frontend/src/features/Map/layer.slice.ts, frontend/src/features/NewFeatures/constants.ts, frontend/src/features/NewFeatures/types.ts, frontend/src/features/Regulation/components/RegulatoryZoneMetadata/regulatoryReferences/RegulatoryReferencesDisplayed.tsx, frontend/src/features/Vessel/components/VesselList/DownloadVesselListModal.tsx, frontend/src/features/Vessel/components/VesselSidebar/actions/TrackRequest/ExportTrack.tsx, frontend/src/features/VesselFilter/components/VesselFilters/FilterParameters.tsx, frontend/src/features/commonComponents/MapPropertyTrigger.tsx, frontend/src/hooks/useTracking.ts, frontend/src/store/reducers.ts, frontend/src/workers/hooks/useGetServiceWorker.tsx
=> Cartographie - Stockage des fonds de cartes en local

frontend/cypress/e2e/main_window/measurement.spec.ts, frontend/cypress/e2e/sidebars/regulatory_layers.spec.ts, frontend/src/features/Measurement/components/MeasurementMapButton/index.tsx, frontend/src/features/Measurement/layers/MeasurementLayer.tsx, frontend/src/features/Measurement/slice.ts, frontend/src/features/Measurement/useCases/addCustomCircleMeasurement.ts, frontend/src/features/Measurement/useCases/saveMeasurement.ts
=> Mesures - Correction de la mesure par lignes brisées

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBLogbookReportRepository.kt
=> Tech - Correction de l'index de la requête logbook

datascience/src/pipeline/sms/malfunction_at_sea_reminder.jinja, datascience/tests/test_data/sms/MALFUNCTION_AT_SEA_REMINDER.txt
=> Mise à jour du message de notification d'avarie VMS

frontend/cypress/e2e/side_window/vessel_list/table.spec.ts, frontend/src/features/Vessel/Vessel.types.ts, frontend/src/features/Vessel/components/ExportVesselListDialog/constants.ts, frontend/src/features/Vessel/components/ExportVesselListDialog/csvMap.ts, frontend/src/features/Vessel/components/ExportVesselListDialog/index.tsx, frontend/src/features/Vessel/components/VesselSidebar/components/actions/TrackRequest/PositionsTable.tsx, frontend/src/features/Vessel/components/VesselSidebar/components/actions/TrackRequest/TableBodyEmptyData.tsx, frontend/src/features/Vessel/components/VesselSidebar/components/actions/TrackRequest/constants.tsx, frontend/src/features/Vessel/components/VesselSidebar/components/actions/TrackRequest/index.tsx, frontend/src/features/Vessel/components/VesselSidebar/components/actions/TrackRequest/types.ts, frontend/src/features/Vessel/vesselApi.ts, frontend/src/features/VesselGroup/components/VesselGroupMenuDialog/index.tsx
- Resolve #4207
- Resolve #4182
----
=> Situation VMS - Ajout de la longueur (export)

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/vessel_group/VesselGroupFilters.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/DistrictRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/district/GetAllDistricts.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetLastPositions.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/DistrictController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/TreeOptionDataOutput.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/Utils.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/cache/CaffeineConfiguration.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaDistrictRepository.kt, backend/src/main/resources/db/testdata/json/V666.31__Insert_dummy_vessel_groups.jsonc, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/TestUtils.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetLastPositionsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/DistrictControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/VesselGroupControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/TestUtils.kt, frontend/cypress/e2e/side_window/vessel_list/table.spec.ts, frontend/src/api/api.ts, frontend/src/api/district.ts, frontend/src/features/Vessel/components/VesselList/FilterBar.tsx, frontend/src/features/Vessel/components/VesselList/FilterTags.tsx, frontend/src/features/Vessel/components/VesselList/constants.ts, frontend/src/features/Vessel/components/VesselList/types.ts, frontend/src/features/Vessel/schemas/VesselLastPositionSchema.ts, frontend/src/features/VesselGroup/components/EditDynamicVesselGroupDialog/index.tsx, frontend/src/features/VesselGroup/components/VesselGroupMenuDialog/VesselGroupRow.tsx, frontend/src/workers/MonitorFishWebWorker.ts, frontend/src/workers/__tests__/__mocks__/dummyLastPositions.ts, frontend/src/workers/__tests__/getFilteredVessels.test.ts
=> Liste des navires et groupes - Ajouter un filtre par quartier

frontend/src/features/MainWindow/components/MapButtons/MapButton.tsx, frontend/src/features/MainWindow/components/MapButtons/shared/MapToolButton.tsx, frontend/src/features/MainWindow/index.tsx, frontend/src/features/NewFeatures/components/NewFeatures.tsx, frontend/src/features/Vessel/components/VesselFiltersHeadband.tsx, frontend/src/features/Vessel/components/VesselList/utils.ts, frontend/src/features/Vessel/slice.ts, frontend/src/features/VesselGroup/components/VesselGroupMapButton.tsx, frontend/src/features/commonStyles/MapComponent.tsx, frontend/src/hooks/useGetTopOffset.tsx
=> Liste des navires - Ajout d'une bannière de réinitialisation des filtres

frontend/src/features/Vessel/components/VesselFiltersHeadband.tsx, frontend/src/hooks/useGetTopOffset.tsx
=> Liste des navires - Correction de la bannière de reset des filtres

infra/local/geometry_simplify_trigger_function.sql
=> Correction des géométries simplifiées invalides

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/config/SecurityConfig.kt, frontend/src/features/Vessel/components/VesselList/columns.tsx, frontend/src/features/VesselGroup/components/EditFixedVesselGroupDialog/index.tsx
- Resolve #4231
- Correction du téléchargement du fichier CSV d'exemple
----
=> Groupes de navires - Corrections

frontend/cypress/e2e/main_window/vessel_sidebar/reporting.spec.ts, frontend/src/features/NewFeatures/constants.ts, frontend/src/features/SideWindow/constants.ts, frontend/src/features/SideWindow/index.tsx
=> Groupes de navires - Ajout du texte de description des groupes fixes

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/last_position/LastPosition.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel_groups/GetAllVesselGroupsWithVessels.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBVesselGroupRepository.kt, backend/src/main/resources/application.properties, frontend/cypress/e2e/side_window/vessel_group/list.spec.ts, frontend/src/features/Vessel/layers/VesselsLabelsLayer/index.tsx, frontend/src/features/Vessel/layers/style.ts, frontend/src/features/Vessel/useCases/rendering/renderVesselAlertAndBeaconMalfunctionFeatures.ts, frontend/src/features/Vessel/useCases/rendering/renderVesselAlertFeatures.ts, frontend/src/features/Vessel/useCases/rendering/renderVesselBeaconMalfunctionFeatures.ts, frontend/src/features/Vessel/useCases/rendering/renderVesselEstimatedPositionFeatures.ts, frontend/src/features/Vessel/useCases/rendering/renderVesselInfractionSuspicionFeatures.ts, frontend/src/features/VesselGroup/components/VesselGroupList/VesselGroupRow.tsx, frontend/src/features/VesselGroup/components/VesselGroupList/index.tsx, frontend/src/store/migrations.ts, frontend/src/store/reducers.ts
- Tech - Suppression des groupes de navires supprimés du localstorage
- Resolve #4254
- resolve #4255
----
=> Tech - Corrections sur les groupes de navires fixes

datascience/src/pipeline/flows/species.py
=> Correction du type d'espèce de `ALB`

.github/workflows/cicd.yml, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaPositionRepositoryITests.kt, frontend/src/features/Regulation/layers/RegulatoryPreviewLayer.tsx, frontend/src/features/Vessel/layers/VesselsEstimatedPositionLayer/constants.ts, frontend/src/features/Vessel/layers/VesselsLabelsLayer/constants.ts, frontend/src/features/Vessel/layers/VesselsTracksLayer/constants.ts
=> Piste navire - Améliorer les performances du rendu quand le nombre de positions est > 5k

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/ActiveVesselDataOutput.kt, frontend/src/features/Regulation/layers/RegulatoryPreviewLayer.tsx, frontend/src/features/Regulation/layers/styles/regulatoryLayer.style.ts, frontend/src/features/Regulation/useCases/getRegulatoryVectorSource.ts, frontend/src/features/Regulation/useCases/getVectorOLLayer.ts
- Amélioration des performances de l'affichage des couches REG
- Application du style directement sur la feature (plus de style function)
- Augmentation du render buffer
----
=> Couches REG - Amélioration des performances de l'affichage

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/ActiveVesselDataOutput.kt, frontend/src/features/Regulation/layers/RegulatoryPreviewLayer.tsx, frontend/src/features/Regulation/layers/styles/regulatoryLayer.style.ts, frontend/src/features/Regulation/useCases/getRegulatoryVectorSource.ts, frontend/src/features/Regulation/useCases/getVectorOLLayer.ts
Reverts MTES-MCT/monitorfish#4283
=> Revert "Couches REG - Amélioration des performances de l'affichage"

frontend/src/features/Vessel/schemas/VesselProfileSchema.ts, frontend/src/features/VesselGroup/components/EditFixedVesselGroupDialog/index.tsx, frontend/src/features/VesselGroup/components/SelectedVesselGroups/useCases/addOrRemoveVesselToGroupFromCheckPicker.ts, frontend/src/features/VesselGroup/useCases/deleteVesselFromVesselGroup.ts
=> Groupes de navires - Corrections sur la fiche navire

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBManualPriorNotificationRepository.kt
This reverts commit 7ca20e689dc955188e9af30962747fe6c79340ef, reversing changes made to d634df9a033b61cc1355a3a17d51db1588cabe4e.
----
=> Revert "Amélioration performances requête préavis (#4299)"

datascience/src/pipeline/flows/risk_factor.py
=> Résolution du bug du flow `risk_factors` qui génère des doublons

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBManualPriorNotificationRepository.kt, infra/docker/docker-compose.cypress.yml, infra/docker/docker-compose.puppeteer.yml
=> Tech - La requête findAllToVerify des PNOs manuels est lente

frontend/cypress/e2e/main_window/vessel_sidebar/resume.spec.ts, frontend/src/features/FleetSegment/components/FleetSegmentsWithTooltip/index.tsx, frontend/src/features/FleetSegment/components/FleetSegmentsWithTooltip/utils.ts, frontend/src/features/MainWindow/components/MapButtons/VesselVisibility/EditVesselVisibility.tsx, frontend/src/features/Map/slice.ts, frontend/src/features/RiskFactor/components/details/ImpactRiskFactorDetails.tsx, frontend/src/features/Vessel/components/VesselLabelOverlay/VesselLabelContent.tsx, frontend/src/features/Vessel/components/VesselLabelOverlay/index.tsx, frontend/src/features/Vessel/components/VesselList/Row.tsx, frontend/src/features/Vessel/components/VesselList/columns.tsx, frontend/src/features/Vessel/layers/VesselsLabelsLayer/utils.ts, frontend/src/features/Vessel/types/vessel.ts
=> Segments - Revoir l'affichage du type de segment recent / courant

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/logbook/LogbookSoftware.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/logbook/Voyage.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetVesselVoyage.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/vessel/GetVesselVoyageByDates.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/outputs/VoyageDataOutput.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/VesselControllerITests.kt, frontend/cypress/e2e/main_window/vessel_sidebar/logbook.spec.ts, frontend/src/features/Logbook/Logbook.types.ts, frontend/src/features/Logbook/components/VesselLogbook/LogbookMessages/index.tsx, frontend/src/features/Logbook/components/VesselLogbook/LogbookSummary/index.tsx, frontend/src/features/Logbook/components/VesselLogbook/utils.ts, frontend/src/features/Logbook/constants.ts, frontend/src/features/Logbook/slice.ts
=> Fiche navire - Afficher le détail des logiciels des messages JPE

infra/remote/backup/pg_backup_rotated.sh
=> Tech - MAJ du backup de la DB

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/reporting/Reporting.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/activity/GetActivityVisualizationFile.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/ActivityVisualizationController.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/ActivityVisualizationEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/entities/ReportingEntity.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaActivityVisualizationRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/interfaces/DBReportingRepository.kt, backend/src/main/resources/db/migration/internal/V0.308__Update_reporting_table.sql, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/api/bff/ActivityVisualizationControllerITests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaReportingRepositoryITests.kt, frontend/cypress/e2e/side_window/mission_form/sea_control.spec.ts, frontend/src/api/__tests__/geoserver.test.ts, frontend/src/api/geoserver.tsx, frontend/src/features/Mission/components/MissionForm/ActionForm/shared/VesselField.tsx, frontend/src/features/Mission/components/MissionForm/ActionList/EnvActionCard.tsx, frontend/src/features/Mission/components/MissionForm/ActionList/FishActionCard.tsx, frontend/src/features/Mission/components/MissionForm/ActionList/utils.tsx, frontend/src/features/Mission/components/MissionForm/shared/FormHead.ts, frontend/src/features/Mission/components/MissionOverlay/MissionDetails.tsx, frontend/src/features/Vessel/components/VesselSidebar/components/Summary.tsx, frontend/src/features/Vessel/types/vessel.ts, frontend/src/workers/serviceWorker.ts
- Resolve #4377
- Resolve #4409
- Resolve #4166
- Resolve #4224
----
=> CR de contrôles - Ajouter le nom du navire sur les navires inconnus

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/mission/mission_actions/actrep/ActivityCode.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/repositories/MissionActionsRepository.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/mission_actions/GetActivityReports.kt, backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaMissionActionsRepository.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/mission_actions/GetActivityReportsUTests.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/infrastructure/database/repositories/JpaMissionActionRepositoryITests.kt, frontend/cypress/e2e/side_window/mission_list/filter_bar.spec.ts, frontend/cypress/mappings/get-mission-6.json, frontend/cypress/mappings/get-missions-by-ids-6.json, frontend/cypress/mappings/get-missions.json
=> Act-Rep - Inclure les contrôles aériens lorsque la mission est JDP

frontend/public/examples/navires_groupe_fixe.csv, frontend/src/features/Vessel/schemas/ActiveVesselSchema.ts, frontend/src/features/VesselGroup/components/EditFixedVesselGroupDialog/__tests__/__mocks__/getVesselsDummyCsv.ts, frontend/src/features/VesselGroup/components/EditFixedVesselGroupDialog/__tests__/utils.test.ts, frontend/src/features/VesselGroup/components/EditFixedVesselGroupDialog/utils.ts
- Resolve #4393
- Suppression des erreurs `zod` lorsque le gear est null dans species_onboard 
----
=> Groupes de navires - Simplification de la création des groupes fixes depuis une liste

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotification.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/CreateOrUpdateManualPriorNotificationUTests.kt, frontend/src/features/Map/useCases/clickOnMapFeature.ts, frontend/src/features/Vessel/useCases/showVesselTrack.ts
- Resolve #4429
- Resolve #4421
----
=> Préavis - Ne pas envoyer le préavis quand on enregistre un préavis 0

frontend/src/features/NewFeatures/constants.ts, frontend/src/features/VesselGroup/components/VesselGroupList/VesselGroupRow.tsx, frontend/src/features/VesselGroup/components/VesselGroupList/index.tsx, frontend/src/features/VesselGroup/components/VesselGroupMenuDialog/VesselGroupRow.tsx
=> Tech - Ajout de statistiques Matomo et affichage des nouvelles fonctionnalités

frontend/cypress/e2e/back_office/control_objective_tables/table.spec.ts, frontend/cypress/e2e/back_office/fleet_segment_table.spec.ts, frontend/cypress/e2e/back_office/regulation_form/creation.spec.ts, frontend/cypress/e2e/main_window/vessel_sidebar/logbook.spec.ts, frontend/cypress/e2e/main_window/vessel_sidebar/resume.spec.ts, frontend/cypress/e2e/side_window/beacon_malfunction/board.spec.ts, frontend/cypress/e2e/side_window/mission_form/land_control.spec.ts, frontend/cypress/e2e/side_window/mission_form/sea_control_edition.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/CustomGlobalStyle.ts, frontend/src/features/BeaconMalfunction/components/BeaconMalfunctionBoard/BeaconMalfunctionCard.tsx, frontend/src/features/BeaconMalfunction/components/BeaconMalfunctionBoard/BeaconMalfunctionDetails.tsx, frontend/src/features/BeaconMalfunction/components/BeaconMalfunctionBoard/VesselStatusSelect.tsx, frontend/src/features/BeaconMalfunction/components/BeaconMalfunctionBoard/VesselStatusSelectValue.tsx, frontend/src/features/BeaconMalfunction/components/BeaconMalfunctionBoard/index.tsx, frontend/src/features/ControlObjective/components/ControlObjectiveTable/ControlPriorityCell.tsx, frontend/src/features/ControlObjective/components/ControlObjectiveTable/SeafrontControlObjectives.tsx, frontend/src/features/Regulation/components/RegulationForm/GearRegulation/RegulatedGear.tsx, frontend/src/features/Regulation/components/RegulationForm/custom_form/CustomSelectComponent.tsx, frontend/src/features/Regulation/components/RegulationForm/custom_form/MenuItem.tsx, frontend/src/features/Regulation/components/RegulationForm/identification/RegulationTopicLine.tsx, frontend/src/features/Regulation/components/RegulationForm/species_regulation/RegulatedSpecies.tsx, frontend/src/features/Regulation/components/RegulationTables/tableCells.tsx, frontend/src/features/Vessel/components/VesselSidebar/components/Equipment/resume/CurrentBeaconMalfunctionBody.tsx, frontend/src/features/commonStyles/Input.style.jsx
=> UI - Utilisation du composant Select de monitor-ui

backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/mission_actions/UpdateMissionAction.kt, backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/mission/mission_actions/UpdateMissionActionUTests.kt
=> Contrôles - Correction de l'ajout du nom de l'espèce dans le contrôle 

frontend/src/features/VesselGroup/components/VesselGroupMenuDialog/index.tsx
=> UI - Résolution du bug d'affichage sur la taille de la liste des groupes lorsqu'il y a un bandeau d'avertissement

frontend/cypress/e2e/side_window/alert_list/alerts_management.spec.ts, frontend/src/features/Alert/components/SideWindowAlerts/AlertManagementForm/Criteria/DistrictCriteria.tsx, frontend/src/features/Alert/components/SideWindowAlerts/AlertManagementForm/constants.ts, frontend/src/features/Alert/components/SideWindowAlerts/AlertManagementForm/index.tsx
=>  Alertes paramétrables - Ajout du critère "Départements et quartiers"

frontend/src/features/Vessel/components/VesselLabelOverlay/VesselLabelContent.tsx
=> Tech - Empêcher le drag du pavillon du navire
